<a href="https://colab.research.google.com/github/sg16022003-pixel/Global-Literacy-Analysis/blob/main/CrossMarketAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cryptocurrency

In [1]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)

In [2]:
all_records=[]
import requests
import time
for page in range(1,6):
    url=f'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=250&order=market_cap_desc&page=1&sparkline=False'
    response=requests.get(url)
    if response.status_code==200:
        data=response.json()
        all_records.extend(data)

In [3]:
len(all_records)

750

In [4]:
from functools import total_ordering
Records=[]
for i in all_records:
    Records.append(dict(ID=i['id'],symbol=i['symbol'],Name=i['name'],current_price=i['current_price'],Market_cap=i['market_cap'],Market_cap_Rank=i['market_cap_rank'],Total_volume=['total_volume'],Circulating_Supply=i['circulating_supply'],Total_supply=i['total_supply'],ath=i['ath'],atl=i['atl'],Last_update=i['last_updated']))
Records

[{'ID': 'bitcoin',
  'symbol': 'btc',
  'Name': 'Bitcoin',
  'current_price': 65241,
  'Market_cap': 1305769714138,
  'Market_cap_Rank': 1,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 19994384.0,
  'Total_supply': 19994503.0,
  'ath': 126080,
  'atl': 67.81,
  'Last_update': '2026-02-25T11:17:33.677Z'},
 {'ID': 'ethereum',
  'symbol': 'eth',
  'Name': 'Ethereum',
  'current_price': 1915.25,
  'Market_cap': 231249290227,
  'Market_cap_Rank': 2,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 120692321.1098494,
  'Total_supply': 120692321.1098494,
  'ath': 4946.05,
  'atl': 0.432979,
  'Last_update': '2026-02-25T11:17:33.538Z'},
 {'ID': 'tether',
  'symbol': 'usdt',
  'Name': 'Tether',
  'current_price': 0.999818,
  'Market_cap': 183589915324,
  'Market_cap_Rank': 3,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 183624238441.843,
  'Total_supply': 189091175734.4462,
  'ath': 1.32,
  'atl': 0.572521,
  'Last_update': '2026-02-25T11:17:33.508Z'},
 {'ID': 'ripple',
  'symbol': 'xrp',
  'Name': 'XRP',
  'current_price': 1.38,
  'Market_cap': 83921821776,
  'Market_cap_Rank': 4,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 61018583977.0,
  'Total_supply': 99985712847.0,
  'ath': 3.65,
  'atl': 0.00268621,
  'Last_update': '2026-02-25T11:17:33.426Z'},
 {'ID': 'binancecoin',
  'symbol': 'bnb',
  'Name': 'BNB',
  'current_price': 602.54,
  'Market_cap': 82128547665,
  'Market_cap_Rank': 5,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 136358928.35,
  'Total_supply': 136358928.35,
  'ath': 1369.99,
  'atl': 0.0398177,
  'Last_update': '2026-02-25T11:17:33.719Z'},
 {'ID': 'usd-coin',
  'symbol': 'usdc',
  'Name': 'USDC',
  'current_price': 0.999803,
  'Market_cap': 74928107847,
  'Market_cap_Rank': 6,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 74939677178.2461,
  'Total_supply': 74942675255.52979,
  'ath': 1.17,
  'atl': 0.877647,
  'Last_update': '2026-02-25T11:17:33.403Z'},
 {'ID': 'solana',
  'symbol': 'sol',
  'Name': 'Solana',
  'current_price': 82.54,
  'Market_cap': 46930667064,
  'Market_cap_Rank': 7,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 568666691.8296871,
  'Total_supply': 621062925.5081047,
  'ath': 293.31,
  'atl': 0.500801,
  'Last_update': '2026-02-25T11:17:33.198Z'},
 {'ID': 'tron',
  'symbol': 'trx',
  'Name': 'TRON',
  'current_price': 0.285999,
  'Market_cap': 27100699815,
  'Market_cap_Rank': 8,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 94736335071.3254,
  'Total_supply': 94737373601.78769,
  'ath': 0.431288,
  'atl': 0.00180434,
  'Last_update': '2026-02-25T11:17:33.050Z'},
 {'ID': 'figure-heloc',
  'symbol': 'figr_heloc',
  'Name': 'Figure Heloc',
  'current_price': 1.034,
  'Market_cap': 15897548936,
  'Market_cap_Rank': 9,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 15376945530.577,
  'Total_supply': 15376945530.577,
  'ath': 1.37,
  'atl': 0.155357,
  'Last_update': '2026-02-25T11:17:32.821Z'},
 {'ID': 'dogecoin',
  'symbol': 'doge',
  'Name': 'Dogecoin',
  'current_price': 0.093661,
  'Market_cap': 15806103829,
  'Market_cap_Rank': 10,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 168830643126.5791,
  'Total_supply': 168883183126.579,
  'ath': 0.731578,
  'atl': 8.69e-05,
  'Last_update': '2026-02-25T11:17:33.081Z'},
 {'ID': 'whitebit',
  'symbol': 'wbt',
  'Name': 'WhiteBIT Coin',
  'current_price': 48.79,
  'Market_cap': 10411231203,
  'Market_cap_Rank': 11,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 213544699.0,
  'Total_supply': 320044699.0,
  'ath': 64.11,
  'atl': 3.06,
  'Last_update': '2026-02-25T11:17:32.864Z'},
 {'ID': 'cardano',
  'symbol': 'ada',
  'Name': 'Cardano',
  'current_price': 0.269048,
  'Market_cap': 9915707181,
  'Market_cap_Rank': 12,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 36813373987.7429,
  'Total_supply': 45000000000.0,
  'ath': 3.09,
  'atl': 0.01925275,
  'Last_update': '2026-02-25T11:17:33.247Z'},
 {'ID': 'usds',
  'symbol': 'usds',
  'Name': 'USDS',
  'current_price': 0.99983,
  'Market_cap': 9901912188,
  'Market_cap_Rank': 13,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 9903494649.085485,
  'Total_supply': 9903494649.085485,
  'ath': 1.057,
  'atl': 0.948265,
  'Last_update': '2026-02-25T11:17:32.876Z'},
 {'ID': 'bitcoin-cash',
  'symbol': 'bch',
  'Name': 'Bitcoin Cash',
  'current_price': 490.93,
  'Market_cap': 9840546329,
  'Market_cap_Rank': 14,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 19999618.64665078,
  'Total_supply': 20000028.02165078,
  'ath': 3785.82,
  'atl': 76.93,
  'Last_update': '2026-02-25T11:17:33.112Z'},
 {'ID': 'leo-token',
  'symbol': 'leo',
  'Name': 'LEO Token',
  'current_price': 8.68,
  'Market_cap': 7998109533,
  'Market_cap_Rank': 15,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 921293554.9,
  'Total_supply': 985239504.0,
  'ath': 10.14,
  'atl': 0.799859,
  'Last_update': '2026-02-25T11:17:32.862Z'},
 {'ID': 'hyperliquid',
  'symbol': 'hype',
  'Name': 'Hyperliquid',
  'current_price': 26.88,
  'Market_cap': 6413995993,
  'Market_cap_Rank': 16,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 238385315.9541414,
  'Total_supply': 962274028.9541414,
  'ath': 59.3,
  'atl': 3.81,
  'Last_update': '2026-02-25T11:17:32.907Z'},
 {'ID': 'monero',
  'symbol': 'xmr',
  'Name': 'Monero',
  'current_price': 340.69,
  'Market_cap': 6285320362,
  'Market_cap_Rank': 17,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 18446744.07370955,
  'Total_supply': 18446744.07370955,
  'ath': 797.73,
  'atl': 0.216177,
  'Last_update': '2026-02-25T11:17:32.917Z'},
 {'ID': 'canton-network',
  'symbol': 'cc',
  'Name': 'Canton',
  'current_price': 0.161067,
  'Market_cap': 6090549626,
  'Market_cap_Rank': 18,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 37824710603.98177,
  'Total_supply': 37824710603.98177,
  'ath': 0.194152,
  'atl': 0.059024,
  'Last_update': '2026-02-25T11:17:33.241Z'},
 {'ID': 'ethena-usde',
  'symbol': 'usde',
  'Name': 'Ethena USDe',
  'current_price': 0.999013,
  'Market_cap': 6079864100,
  'Market_cap_Rank': 19,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 6082844092.655022,
  'Total_supply': 6082844092.655022,
  'ath': 1.034,
  'atl': 0.929486,
  'Last_update': '2026-02-25T11:17:33.030Z'},
 {'ID': 'chainlink',
  'symbol': 'link',
  'Name': 'Chainlink',
  'current_price': 8.57,
  'Market_cap': 6071900355,
  'Market_cap_Rank': 20,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 708099970.4525867,
  'Total_supply': 1000000000.0,
  'ath': 52.7,
  'atl': 0.148183,
  'Last_update': '2026-02-25T11:17:33.285Z'},
 {'ID': 'stellar',
  'symbol': 'xlm',
  'Name': 'Stellar',
  'current_price': 0.15383,
  'Market_cap': 5058318572,
  'Market_cap_Rank': 21,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 32858230079.69073,
  'Total_supply': 50001786883.65895,
  'ath': 0.875563,
  'atl': 0.00047612,
  'Last_update': '2026-02-25T11:17:34.222Z'},
 {'ID': 'usd1-wlfi',
  'symbol': 'usd1',
  'Name': 'USD1',
  'current_price': 0.999674,
  'Market_cap': 4697762472,
  'Market_cap_Rank': 22,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 4699263074.994215,
  'Total_supply': 4699263074.994215,
  'ath': 1.025,
  'atl': 0.989633,
  'Last_update': '2026-02-25T11:17:33.295Z'},
 {'ID': 'rain',
  'symbol': 'rain',
  'Name': 'Rain',
  'current_price': 0.00933754,
  'Market_cap': 4457810341,
  'Market_cap_Rank': 23,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 477920317604.2821,
  'Total_supply': 1149928998506.933,
  'ath': 0.01090099,
  'atl': 0.00222126,
  'Last_update': '2026-02-25T11:17:32.916Z'},
 {'ID': 'dai',
  'symbol': 'dai',
  'Name': 'Dai',
  'current_price': 0.999104,
  'Market_cap': 4198243104,
  'Market_cap_Rank': 25,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 4200127771.101068,
  'Total_supply': 4184991951.07591,
  'ath': 1.22,
  'atl': 0.88196,
  'Last_update': '2026-02-25T11:17:33.016Z'},
 {'ID': 'hedera-hashgraph',
  'symbol': 'hbar',
  'Name': 'Hedera',
  'current_price': 0.0975,
  'Market_cap': 4198224496,
  'Market_cap_Rank': 24,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 43003421569.30774,
  'Total_supply': 50000000000.0,
  'ath': 0.569229,
  'atl': 0.00986111,
  'Last_update': '2026-02-25T11:17:36.773Z'},
 {'ID': 'paypal-usd',
  'symbol': 'pyusd',
  'Name': 'PayPal USD',
  'current_price': 1.0,
  'Market_cap': 4112377281,
  'Market_cap_Rank': 26,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 4110727264.903578,
  'Total_supply': 4110727264.903578,
  'ath': 1.021,
  'atl': 0.959426,
  'Last_update': '2026-02-25T11:17:32.990Z'},
 {'ID': 'litecoin',
  'symbol': 'ltc',
  'Name': 'Litecoin',
  'current_price': 53.26,
  'Market_cap': 4094616588,
  'Market_cap_Rank': 27,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 76887364.48347135,
  'Total_supply': 76887364.48347135,
  'ath': 410.26,
  'atl': 1.15,
  'Last_update': '2026-02-25T11:17:33.262Z'},
 {'ID': 'zcash',
  'symbol': 'zec',
  'Name': 'Zcash',
  'current_price': 236.96,
  'Market_cap': 3929926907,
  'Market_cap_Rank': 28,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 16570357.9780448,
  'Total_supply': 16571789.2280448,
  'ath': 3191.93,
  'atl': 16.08,
  'Last_update': '2026-02-25T11:17:33.043Z'},
 {'ID': 'avalanche-2',
  'symbol': 'avax',
  'Name': 'Avalanche',
  'current_price': 8.8,
  'Market_cap': 3799499460,
  'Market_cap_Rank': 29,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 431771961.1772119,
  'Total_supply': 463441061.1772119,
  'ath': 144.96,
  'atl': 2.8,
  'Last_update': '2026-02-25T11:17:33.334Z'},
 {'ID': 'shiba-inu',
  'symbol': 'shib',
  'Name': 'Shiba Inu',
  'current_price': 5.99e-06,
  'Market_cap': 3526140071,
  'Market_cap_Rank': 30,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 589243856550788.6,
  'Total_supply': 589500398317916.9,
  'ath': 8.616e-05,
  'atl': 5.6366e-11,
  'Last_update': '2026-02-25T11:17:33.633Z'},
 {'ID': 'sui',
  'symbol': 'sui',
  'Name': 'Sui',
  'current_price': 0.891668,
  'Market_cap': 3430238968,
  'Market_cap_Rank': 31,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 3846172527.429665,
  'Total_supply': 10000000000.0,
  'ath': 5.35,
  'atl': 0.364846,
  'Last_update': '2026-02-25T11:17:33.996Z'},
 {'ID': 'the-open-network',
  'symbol': 'ton',
  'Name': 'Toncoin',
  'current_price': 1.28,
  'Market_cap': 3144288771,
  'Market_cap_Rank': 32,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 2452216167.772734,
  'Total_supply': 5155133531.653379,
  'ath': 8.25,
  'atl': 0.519364,
  'Last_update': '2026-02-25T11:17:34.089Z'},
 {'ID': 'world-liberty-financial',
  'symbol': 'wlfi',
  'Name': 'World Liberty Financial',
  'current_price': 0.11357,
  'Market_cap': 3140256465,
  'Market_cap_Rank': 33,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 27660802912.0,
  'Total_supply': 100000000000.0,
  'ath': 0.331336,
  'atl': 0.098308,
  'Last_update': '2026-02-25T11:17:33.192Z'},
 {'ID': 'crypto-com-chain',
  'symbol': 'cro',
  'Name': 'Cronos',
  'current_price': 0.075524,
  'Market_cap': 3101320446,
  'Market_cap_Rank': 34,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 41057756107.58584,
  'Total_supply': 98423963516.80173,
  'ath': 0.965407,
  'atl': 0.0121196,
  'Last_update': '2026-02-25T11:17:34.607Z'},
 {'ID': 'tether-gold',
  'symbol': 'xaut',
  'Name': 'Tether Gold',
  'current_price': 5148.35,
  'Market_cap': 2682076775,
  'Market_cap_Rank': 35,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 520825.641697,
  'Total_supply': 712747.089,
  'ath': 5596.7,
  'atl': 1447.84,
  'Last_update': '2026-02-25T11:17:34.565Z'},
 {'ID': 'memecore',
  'symbol': 'm',
  'Name': 'MemeCore',
  'current_price': 1.43,
  'Market_cap': 2498078441,
  'Market_cap_Rank': 36,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1739638322.626626,
  'Total_supply': 5339638316.928434,
  'ath': 2.96,
  'atl': 0.04746135,
  'Last_update': '2026-02-25T11:17:33.457Z'},
 {'ID': 'pax-gold',
  'symbol': 'paxg',
  'Name': 'PAX Gold',
  'current_price': 5184.15,
  'Market_cap': 2411687075,
  'Market_cap_Rank': 37,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 465073.822,
  'Total_supply': 465073.822,
  'ath': 5619.09,
  'atl': 1399.64,
  'Last_update': '2026-02-25T11:17:33.391Z'},
 {'ID': 'uniswap',
  'symbol': 'uni',
  'Name': 'Uniswap',
  'current_price': 3.54,
  'Market_cap': 2243463253,
  'Market_cap_Rank': 38,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 633648762.0380214,
  'Total_supply': 898618420.0366304,
  'ath': 44.92,
  'atl': 1.03,
  'Last_update': '2026-02-25T11:17:34.038Z'},
 {'ID': 'polkadot',
  'symbol': 'dot',
  'Name': 'Polkadot',
  'current_price': 1.33,
  'Market_cap': 2219723396,
  'Market_cap_Rank': 39,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1668910580.175999,
  'Total_supply': 1668910580.175999,
  'ath': 54.98,
  'atl': 1.15,
  'Last_update': '2026-02-25T11:17:33.145Z'},
 {'ID': 'mantle',
  'symbol': 'mnt',
  'Name': 'Mantle',
  'current_price': 0.598534,
  'Market_cap': 1947015250,
  'Market_cap_Rank': 40,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 3252944055.63684,
  'Total_supply': 6219316794.889999,
  'ath': 2.86,
  'atl': 0.307978,
  'Last_update': '2026-02-25T11:17:33.071Z'},
 {'ID': 'blackrock-usd-institutional-digital-liquidity-fund',
  'symbol': 'buidl',
  'Name': 'BlackRock USD Institutional Digital Liquidity Fund',
  'current_price': 1.0,
  'Market_cap': 1939526802,
  'Market_cap_Rank': 41,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1939526801.790448,
  'Total_supply': 1939526801.790448,
  'ath': 1.0,
  'atl': 1.0,
  'Last_update': '2026-02-25T11:15:07.668Z'},
 {'ID': 'aave',
  'symbol': 'aave',
  'Name': 'Aave',
  'current_price': 115.83,
  'Market_cap': 1759513680,
  'Market_cap_Rank': 42,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 15190749.804643761,
  'Total_supply': 16000000.0,
  'ath': 661.69,
  'atl': 26.02,
  'Last_update': '2026-02-25T11:17:33.343Z'},
 {'ID': 'falcon-finance',
  'symbol': 'usdf',
  'Name': 'Falcon USD',
  'current_price': 0.997256,
  'Market_cap': 1751284043,
  'Market_cap_Rank': 43,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1756126391.707937,
  'Total_supply': 1756126391.707937,
  'ath': 1.075,
  'atl': 0.943422,
  'Last_update': '2026-02-25T11:17:33.265Z'},
 {'ID': 'aster-2',
  'symbol': 'aster',
  'Name': 'Aster',
  'current_price': 0.691386,
  'Market_cap': 1696178040,
  'Market_cap_Rank': 44,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 2454947754.91,
  'Total_supply': 7822985112.446448,
  'ath': 2.41,
  'atl': 0.099713,
  'Last_update': '2026-02-25T11:17:33.110Z'},
 {'ID': 'bittensor',
  'symbol': 'tao',
  'Name': 'Bittensor',
  'current_price': 175.88,
  'Market_cap': 1689116967,
  'Market_cap_Rank': 45,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 9597491.0,
  'Total_supply': 21000000.0,
  'ath': 757.6,
  'atl': 30.83,
  'Last_update': '2026-02-25T11:17:33.858Z'},
 {'ID': 'pepe',
  'symbol': 'pepe',
  'Name': 'Pepe',
  'current_price': 3.98e-06,
  'Market_cap': 1678480534,
  'Market_cap_Rank': 46,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 420690000000000.0,
  'Total_supply': 420690000000000.0,
  'ath': 2.803e-05,
  'atl': 5.5142e-08,
  'Last_update': '2026-02-25T11:17:33.265Z'},
 {'ID': 'global-dollar',
  'symbol': 'usdg',
  'Name': 'Global Dollar',
  'current_price': 0.999862,
  'Market_cap': 1623195707,
  'Market_cap_Rank': 47,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1623447249.938488,
  'Total_supply': 1623447249.938488,
  'ath': 1.65,
  'atl': 0.907561,
  'Last_update': '2026-02-25T11:17:33.084Z'},
 {'ID': 'hashnote-usyc',
  'symbol': 'usyc',
  'Name': 'Circle USYC',
  'current_price': 1.12,
  'Market_cap': 1588052579,
  'Market_cap_Rank': 48,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1553620528.721001,
  'Total_supply': 1553620528.721001,
  'ath': 1.12,
  'atl': 1.026,
  'Last_update': '2026-02-10T05:42:11.457Z'},
 {'ID': 'okb',
  'symbol': 'okb',
  'Name': 'OKB',
  'current_price': 75.36,
  'Market_cap': 1583223025,
  'Market_cap_Rank': 49,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 21000000.0,
  'Total_supply': 21000000.0,
  'ath': 255.5,
  'atl': 0.580608,
  'Last_update': '2026-02-25T11:17:33.328Z'},
 {'ID': 'ripple-usd',
  'symbol': 'rlusd',
  'Name': 'Ripple USD',
  'current_price': 0.999988,
  'Market_cap': 1558337527,
  'Market_cap_Rank': 50,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1558420615.127497,
  'Total_supply': 1558420615.127497,
  'ath': 1.073,
  'atl': 0.962292,
  'Last_update': '2026-02-25T11:17:36.333Z'},
 {'ID': 'bitget-token',
  'symbol': 'bgb',
  'Name': 'Bitget Token',
  'current_price': 2.22,
  'Market_cap': 1552174769,
  'Market_cap_Rank': 51,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 699992035.9787906,
  'Total_supply': 916931610.9787906,
  'ath': 8.45,
  'atl': 0.0142795,
  'Last_update': '2026-02-25T11:17:36.135Z'},
 {'ID': 'pi-network',
  'symbol': 'pi',
  'Name': 'Pi Network',
  'current_price': 0.167204,
  'Market_cap': 1545607295,
  'Market_cap_Rank': 52,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 9262488873.294975,
  'Total_supply': 14249982881.99227,
  'ath': 2.99,
  'atl': 0.131244,
  'Last_update': '2026-02-25T11:17:33.279Z'},
 {'ID': 'sky',
  'symbol': 'sky',
  'Name': 'Sky',
  'current_price': 0.066428,
  'Market_cap': 1528918240,
  'Market_cap_Rank': 53,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 23032459026.32462,
  'Total_supply': 23462665147.36596,
  'ath': 0.100535,
  'atl': 0.03582727,
  'Last_update': '2026-02-25T11:17:33.167Z'},
 {'ID': 'htx-dao',
  'symbol': 'htx',
  'Name': 'HTX DAO',
  'current_price': 1.65e-06,
  'Market_cap': 1516468419,
  'Market_cap_Rank': 54,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 916533066327098.8,
  'Total_supply': 916533066327098.8,
  'ath': 3.75e-06,
  'atl': 8.00816e-07,
  'Last_update': '2026-02-25T11:17:33.219Z'},
 {'ID': 'ethereum-classic',
  'symbol': 'etc',
  'Name': 'Ethereum Classic',
  'current_price': 8.5,
  'Market_cap': 1322389722,
  'Market_cap_Rank': 55,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 155666802.8652896,
  'Total_supply': 155668999.2173645,
  'ath': 167.09,
  'atl': 0.615038,
  'Last_update': '2026-02-25T11:17:33.141Z'},
 {'ID': 'bfusd',
  'symbol': 'bfusd',
  'Name': 'BFUSD',
  'current_price': 0.999291,
  'Market_cap': 1319062804,
  'Market_cap_Rank': 56,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1320000000.0,
  'Total_supply': 1320000000.0,
  'ath': 1.007,
  'atl': 0.997035,
  'Last_update': '2026-02-25T11:17:33.300Z'},
 {'ID': 'near',
  'symbol': 'near',
  'Name': 'NEAR Protocol',
  'current_price': 1.011,
  'Market_cap': 1302656583,
  'Market_cap_Rank': 57,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 1288676162.0,
  'Total_supply': 1288676471.0,
  'ath': 20.44,
  'atl': 0.526762,
  'Last_update': '2026-02-25T11:17:34.719Z'},
 {'ID': 'ondo-finance',
  'symbol': 'ondo',
  'Name': 'Ondo',
  'current_price': 0.255441,
  'Market_cap': 1244184949,
  'Market_cap_Rank': 58,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 4869330647.0,
  'Total_supply': 10000000000.0,
  'ath': 2.14,
  'atl': 0.082171,
  'Last_update': '2026-02-25T11:17:33.597Z'},
 {'ID': 'polygon-ecosystem-token',
  'symbol': 'pol',
  'Name': 'POL (ex-MATIC)',
  'current_price': 0.11312,
  'Market_cap': 1202217089,
  'Market_cap_Rank': 59,
  'Total_volume': ['total_volume'],
  'Circulating_Supply': 10597901325.94426,
  'Total_supply': 10597901325.94426,
  'ath': 1.29,
  'atl': 0.086938,
  'Last_update': '2026-02-25T11:17:36.159Z'},
 {'ID': 'internet-computer',

In [5]:
len(all_records)

750

In [6]:
records=[]
for i in data:
    records.append(dict(
        ID=i['id'],
        symbol=i['symbol']))
records

[{'ID': 'bitcoin', 'symbol': 'btc'},
 {'ID': 'ethereum', 'symbol': 'eth'},
 {'ID': 'tether', 'symbol': 'usdt'},
 {'ID': 'ripple', 'symbol': 'xrp'},
 {'ID': 'binancecoin', 'symbol': 'bnb'},
 {'ID': 'usd-coin', 'symbol': 'usdc'},
 {'ID': 'solana', 'symbol': 'sol'},
 {'ID': 'tron', 'symbol': 'trx'},
 {'ID': 'figure-heloc', 'symbol': 'figr_heloc'},
 {'ID': 'dogecoin', 'symbol': 'doge'},
 {'ID': 'whitebit', 'symbol': 'wbt'},
 {'ID': 'cardano', 'symbol': 'ada'},
 {'ID': 'usds', 'symbol': 'usds'},
 {'ID': 'bitcoin-cash', 'symbol': 'bch'},
 {'ID': 'leo-token', 'symbol': 'leo'},
 {'ID': 'hyperliquid', 'symbol': 'hype'},
 {'ID': 'monero', 'symbol': 'xmr'},
 {'ID': 'canton-network', 'symbol': 'cc'},
 {'ID': 'ethena-usde', 'symbol': 'usde'},
 {'ID': 'chainlink', 'symbol': 'link'},
 {'ID': 'stellar', 'symbol': 'xlm'},
 {'ID': 'usd1-wlfi', 'symbol': 'usd1'},
 {'ID': 'rain', 'symbol': 'rain'},
 {'ID': 'dai', 'symbol': 'dai'},
 {'ID': 'hedera-hashgraph', 'symbol': 'hbar'},
 {'ID': 'paypal-usd', 'symbol': 'pyusd'},
 {'ID': 'litecoin', 'symbol': 'ltc'},
 {'ID': 'zcash', 'symbol': 'zec'},
 {'ID': 'avalanche-2', 'symbol': 'avax'},
 {'ID': 'shiba-inu', 'symbol': 'shib'},
 {'ID': 'sui', 'symbol': 'sui'},
 {'ID': 'the-open-network', 'symbol': 'ton'},
 {'ID': 'world-liberty-financial', 'symbol': 'wlfi'},
 {'ID': 'crypto-com-chain', 'symbol': 'cro'},
 {'ID': 'tether-gold', 'symbol': 'xaut'},
 {'ID': 'memecore', 'symbol': 'm'},
 {'ID': 'pax-gold', 'symbol': 'paxg'},
 {'ID': 'uniswap', 'symbol': 'uni'},
 {'ID': 'polkadot', 'symbol': 'dot'},
 {'ID': 'mantle', 'symbol': 'mnt'},
 {'ID': 'blackrock-usd-institutional-digital-liquidity-fund',
  'symbol': 'buidl'},
 {'ID': 'aave', 'symbol': 'aave'},
 {'ID': 'falcon-finance', 'symbol': 'usdf'},
 {'ID': 'aster-2', 'symbol': 'aster'},
 {'ID': 'bittensor', 'symbol': 'tao'},
 {'ID': 'pepe', 'symbol': 'pepe'},
 {'ID': 'global-dollar', 'symbol': 'usdg'},
 {'ID': 'hashnote-usyc', 'symbol': 'usyc'},
 {'ID': 'okb', 'symbol': 'okb'},
 {'ID': 'ripple-usd', 'symbol': 'rlusd'},
 {'ID': 'bitget-token', 'symbol': 'bgb'},
 {'ID': 'pi-network', 'symbol': 'pi'},
 {'ID': 'sky', 'symbol': 'sky'},
 {'ID': 'htx-dao', 'symbol': 'htx'},
 {'ID': 'ethereum-classic', 'symbol': 'etc'},
 {'ID': 'bfusd', 'symbol': 'bfusd'},
 {'ID': 'near', 'symbol': 'near'},
 {'ID': 'ondo-finance', 'symbol': 'ondo'},
 {'ID': 'polygon-ecosystem-token', 'symbol': 'pol'},
 {'ID': 'internet-computer', 'symbol': 'icp'},
 {'ID': 'superstate-short-duration-us-government-securities-fund-ustb',
  'symbol': 'ustb'},
 {'ID': 'worldcoin-wld', 'symbol': 'wld'},
 {'ID': 'gatechain-token', 'symbol': 'gt'},
 {'ID': 'kucoin-shares', 'symbol': 'kcs'},
 {'ID': 'pump-fun', 'symbol': 'pump'},
 {'ID': 'cosmos', 'symbol': 'atom'},
 {'ID': 'midnight-3', 'symbol': 'night'},
 {'ID': 'hash-2', 'symbol': 'hash'},
 {'ID': 'quant-network', 'symbol': 'qnt'},
 {'ID': 'nexo', 'symbol': 'nexo'},
 {'ID': 'usdtb', 'symbol': 'usdtb'},
 {'ID': 'ethena', 'symbol': 'ena'},
 {'ID': 'official-trump', 'symbol': 'trump'},
 {'ID': 'eutbl', 'symbol': 'eutbl'},
 {'ID': 'flare-networks', 'symbol': 'flr'},
 {'ID': 'kaspa', 'symbol': 'kas'},
 {'ID': 'algorand', 'symbol': 'algo'},
 {'ID': 'pippin', 'symbol': 'pippin'},
 {'ID': 'usdd', 'symbol': 'usdd'},
 {'ID': 'ousg', 'symbol': 'ousg'},
 {'ID': 'render-token', 'symbol': 'render'},
 {'ID': 'janus-henderson-anemoy-aaa-clo-fund', 'symbol': 'jaaa'},
 {'ID': 'ondo-us-dollar-yield', 'symbol': 'usdy'},
 {'ID': 'filecoin', 'symbol': 'fil'},
 {'ID': 'aptos', 'symbol': 'apt'},
 {'ID': 'xdce-crowd-sale', 'symbol': 'xdc'},
 {'ID': 'morpho', 'symbol': 'morpho'},
 {'ID': 'vechain', 'symbol': 'vet'},
 {'ID': 'beldex', 'symbol': 'bdx'},
 {'ID': 'janus-henderson-anemoy-treasury-fund', 'symbol': 'jtrsy'},
 {'ID': 'usual-usd', 'symbol': 'usd0'},
 {'ID': 'arbitrum', 'symbol': 'arb'},
 {'ID': 'gho', 'symbol': 'gho'},
 {'ID': 'stable-2', 'symbol': 'stable'},
 {'ID': 'bonk', 'symbol': 'bonk'},
 {'ID': 'a7a5', 'symbol': 'a7a5'},
 {'ID': 'true-usd', 'symbol': 'tusd'},
 {'ID': 'decred', 'symbol': 'dcr'},
 {'ID': 'jupiter-exchange-solana', 'symbol': 'jup'},
 {'ID': 'kite-2', 'symbol': 'kite'},
 {'ID': 'fasttoken', 'symbol': 'ftn'},
 {'ID': 'usdai', 'symbol': 'usdai'},
 {'ID': 'euro-coin', 'symbol': 'eurc'},
 {'ID': 'sei-network', 'symbol': 'sei'},
 {'ID': 'blockstack', 'symbol': 'stx'},
 {'ID': 'virtual-protocol', 'symbol': 'virtual'},
 {'ID': 'dash', 'symbol': 'dash'},
 {'ID': 'pudgy-penguins', 'symbol': 'pengu'},
 {'ID': 'pancakeswap-token', 'symbol': 'cake'},
 {'ID': 'tezos', 'symbol': 'xtz'},
 {'ID': 'just', 'symbol': 'jst'},
 {'ID': 'kinesis-gold', 'symbol': 'kau'},
 {'ID': 'first-digital-usd', 'symbol': 'fdusd'},
 {'ID': 'ether-fi', 'symbol': 'ethfi'},
 {'ID': 'story-2', 'symbol': 'ip'},
 {'ID': 'curve-dao-token', 'symbol': 'crv'},
 {'ID': 'fetch-ai', 'symbol': 'fet'},
 {'ID': 'c8ntinuum', 'symbol': 'ctm'},
 {'ID': 'lighter', 'symbol': 'lit'},
 {'ID': 'chiliz', 'symbol': 'chz'},
 {'ID': 'hastra-prime', 'symbol': 'prime'},
 {'ID': 'usx', 'symbol': 'usx'},
 {'ID': 'apenft', 'symbol': 'nft'},
 {'ID': 'gnosis', 'symbol': 'gno'},
 {'ID': 'bittorrent', 'symbol': 'btt'},
 {'ID': 'bitcoin-cash-sv', 'symbol': 'bsv'},
 {'ID': 'kaia', 'symbol': 'kaia'},
 {'ID': 'sun-token', 'symbol': 'sun'},
 {'ID': 'injective-protocol', 'symbol': 'inj'},
 {'ID': 'adi-token', 'symbol': 'adi'},
 {'ID': 'aerodrome-finance', 'symbol': 'aero'},
 {'ID': 'layerzero', 'symbol': 'zro'},
 {'ID': 'pyth-network', 'symbol': 'pyth'},
 {'ID': 'iota', 'symbol': 'iota'},
 {'ID': 'crvusd', 'symbol': 'crvusd'},
 {'ID': 'jasmycoin', 'symbol': 'jasmy'},
 {'ID': 'the-graph', 'symbol': 'grt'},
 {'ID': 'celestia', 'symbol': 'tia'},
 {'ID': 'floki', 'symbol': 'floki'},
 {'ID': 'spx6900', 'symbol': 'spx'},
 {'ID': 'frax', 'symbol': 'frax'},
 {'ID': 'siren-2', 'symbol': 'siren'},
 {'ID': 'olympus', 'symbol': 'ohm'},
 {'ID': 'syrup', 'symbol': 'syrup'},
 {'ID': 'btse-token', 'symbol': 'btse'},
 {'ID': 'doublezero', 'symbol': '2z'},
 {'ID': 'lido-dao', 'symbol': 'ldo'},
 {'ID': 'conflux-token', 'symbol': 'cfx'},
 {'ID': 'helium', 'symbol': 'hnt'},
 {'ID': 'optimism', 'symbol': 'op'},
 {'ID': 'humanity', 'symbol': 'h'},
 {'ID': 'newton-project', 'symbol': 'ab'},
 {'ID': 'telcoin', 'symbol': 'tel'},
 {'ID': 'ethereum-name-service', 'symbol': 'ens'},
 {'ID': 'nusd-2', 'symbol': 'nusd'},
 {'ID': 'starknet', 'symbol': 'strk'},
 {'ID': 'axie-infinity', 'symbol': 'axs'},
 {'ID': 'ylds', 'symbol': 'ylds'},
 {'ID': 'monad', 'symbol': 'mon'},
 {'ID': 'undeads-games', 'symbol': 'uds'},
 {'ID': 'usda-2', 'symbol': 'usda'},
 {'ID': 'spiko-us-t-bills-money-market-fund', 'symbol': 'ustbl'},
 {'ID': 'agora-dollar', 'symbol': 'ausd'},
 {'ID': 'the-sandbox', 'symbol': 'sand'},
 {'ID': 'trust-wallet-token', 'symbol': 'twt'},
 {'ID': 'pendle', 'symbol': 'pendle'},
 {'ID': 'blockchain-capital', 'symbol': 'bcap'},
 {'ID': 'zebec-network', 'symbol': 'zbcn'},
 {'ID': 'flying-tulip', 'symbol': 'ft'},
 {'ID': 'ape-and-pepe', 'symbol': 'apepe'},
 {'ID': 'plasma', 'symbol': 'xpl'},
 {'ID': 'dogwifcoin', 'symbol': 'wif'},
 {'ID': 'ultima', 'symbol': 'ultima'},
 {'ID': 'swissborg', 'symbol': 'borg'},
 {'ID': 'terra-luna', 'symbol': 'lunc'},
 {'ID': 'vision-3', 'symbol': 'vsn'},
 {'ID': 'tradable-na-rent-financing-platform-sstn', 'symbol': 'pc0000031'},
 {'ID': 'neo', 'symbol': 'neo'},
 {'ID': 'river', 'symbol': 'river'},
 {'ID': 'theta-token', 'symbol': 'theta'},
 {'ID': 'zksync', 'symbol': 'zk'},
 {'ID': 'falcon-finance-ff', 'symbol': 'ff'},
 {'ID': 'basic-attention-token', 'symbol': 'bat'},
 {'ID': 'chain-2', 'symbol': 'xcn'},
 {'ID': 'decentraland', 'symbol': 'mana'},
 {'ID': 'fidelity-digital-interest-token', 'symbol': 'fdit'},
 {'ID': 'venice-token', 'symbol': 'vvv'},
 {'ID': 'ribbita-by-virtuals', 'symbol': 'tibbir'},
 {'ID': 'compound-governance-token', 'symbol': 'comp'},
 {'ID': 'lombard-protocol', 'symbol': 'bard'},
 {'ID': 'infinifi-usd', 'symbol': 'iusd'},
 {'ID': 'sentient', 'symbol': 'sent'},
 {'ID': 'convex-finance', 'symbol': 'cvx'},
 {'ID': 'wefi', 'symbol': 'wfi'},
 {'ID': 'gala', 'symbol': 'gala'},
 {'ID': 'the9bit', 'symbol': '9bit'},
 {'ID': 'mx-token', 'symbol': 'mx'},
 {'ID': 'raydium', 'symbol': 'ray'},
 {'ID': 'bnb48-club-token', 'symbol': 'koge'},
 {'ID': 'reallink', 'symbol': 'real'},
 {'ID': 'instadapp', 'symbol': 'fluid'},
 {'ID': 'satoshi-stablecoin', 'symbol': 'satusd'},
 {'ID': 'dexe', 'symbol': 'dexe'},
 {'ID': 'stasis-eurs', 'symbol': 'eurs'},
 {'ID': 'fartcoin', 'symbol': 'fartcoin'},
 {'ID': 'power-protocol', 'symbol': 'power'},
 {'ID': 'ecash', 'symbol': 'xec'},
 {'ID': 'sonic-3', 'symbol': 's'},
 {'ID': 'astherus-usdf', 'symbol': 'usdf'},
 {'ID': 'gusd', 'symbol': 'gusd'},
 {'ID': 'golem', 'symbol': 'glm'},
 {'ID': 'theo-short-duration-us-treasury-fund', 'symbol': 'thbill'},
 {'ID': 'immutable-x', 'symbol': 'imx'},
 {'ID': 'wemix-token', 'symbol': 'wemix'},
 {'ID': 'thorchain', 'symbol': 'rune'},
 {'ID': 'origintrail', 'symbol': 'trac'},
 {'ID': 'zero-gravity', 'symbol': '0g'},
 {'ID': 'rollbit-coin', 'symbol': 'rlb'},
 {'ID': 'seeker', 'symbol': 'skr'},
 {'ID': 'berachain-bera', 'symbol': 'bera'},
 {'ID': 'vaulta', 'symbol': 'a'},
 {'ID': 'apollo-diversified-credit-securitize-fund', 'symbol': 'acred'},
 {'ID': 'elrond-erd-2', 'symbol': 'egld'},
 {'ID': 'gmt-token', 'symbol': 'gomining'},
 {'ID': 'jito-governance-token', 'symbol': 'jto'},
 {'ID': 'coco-2', 'symbol': 'coco'},
 {'ID': 'safepal', 'symbol': 'sfp'},
 {'ID': '1inch', 'symbol': '1inch'},
 {'ID': 'havven', 'symbol': 'snx'},
 {'ID': 'build-on', 'symbol': 'b'},
 {'ID': 'ozone-chain', 'symbol': 'ozo'},
 {'ID': 'keeta', 'symbol': 'kta'},
 {'ID': 'amp-token', 'symbol': 'amp'},
 {'ID': 'zano', 'symbol': 'zano'},
 {'ID': 'cow-protocol', 'symbol': 'cow'},
 {'ID': 'ai-rig-complex', 'symbol': 'arc'},
 {'ID': 'dola-usd', 'symbol': 'dola'},
 {'ID': 'walrus-2', 'symbol': 'wal'},
 {'ID': 'loaded-lions', 'symbol': 'lion'},
 {'ID': 'pleasing-usd', 'symbol': 'pusd'},
 {'ID': 'comedian', 'symbol': 'ban'},
 {'ID': 'cap-usd', 'symbol': 'cusd'},
 {'ID': 'livepeer', 'symbol': 'lpt'},
 {'ID': 'cash-4', 'symbol': 'cash'},
 {'ID': 'mimblewimblecoin', 'symbol': 'mwc'},
 {'ID': 'arweave', 'symbol': 'ar'},
 {'ID': 'eigenlayer', 'symbol': 'eigen'},
 {'ID': 'quantum-resistant-ledger', 'symbol': 'qrl'},
 {'ID': 're-protocol-reusd', 'symbol': 'reusd'},
 {'ID': 'frax-usd', 'symbol': 'frxusd'}]

In [7]:
import pandas as pd
df=pd.DataFrame(records)
df

                           ID  symbol
0                     bitcoin     btc
1                    ethereum     eth
2                      tether    usdt
3                      ripple     xrp
4                 binancecoin     bnb
..                        ...     ...
245                   arweave      ar
246                eigenlayer   eigen
247  quantum-resistant-ledger     qrl
248         re-protocol-reusd   reusd
249                  frax-usd  frxusd

[250 rows x 2 columns]

In [8]:
records=[]
for i in data:
    records.append(dict( ID=i['id'],
        Market_cap_Rank=i['market_cap_rank']))
records

[{'ID': 'bitcoin', 'Market_cap_Rank': 1},
 {'ID': 'ethereum', 'Market_cap_Rank': 2},
 {'ID': 'tether', 'Market_cap_Rank': 3},
 {'ID': 'ripple', 'Market_cap_Rank': 4},
 {'ID': 'binancecoin', 'Market_cap_Rank': 5},
 {'ID': 'usd-coin', 'Market_cap_Rank': 6},
 {'ID': 'solana', 'Market_cap_Rank': 7},
 {'ID': 'tron', 'Market_cap_Rank': 8},
 {'ID': 'figure-heloc', 'Market_cap_Rank': 9},
 {'ID': 'dogecoin', 'Market_cap_Rank': 10},
 {'ID': 'whitebit', 'Market_cap_Rank': 11},
 {'ID': 'cardano', 'Market_cap_Rank': 12},
 {'ID': 'usds', 'Market_cap_Rank': 13},
 {'ID': 'bitcoin-cash', 'Market_cap_Rank': 14},
 {'ID': 'leo-token', 'Market_cap_Rank': 15},
 {'ID': 'hyperliquid', 'Market_cap_Rank': 16},
 {'ID': 'monero', 'Market_cap_Rank': 17},
 {'ID': 'canton-network', 'Market_cap_Rank': 18},
 {'ID': 'ethena-usde', 'Market_cap_Rank': 19},
 {'ID': 'chainlink', 'Market_cap_Rank': 20},
 {'ID': 'stellar', 'Market_cap_Rank': 21},
 {'ID': 'usd1-wlfi', 'Market_cap_Rank': 22},
 {'ID': 'rain', 'Market_cap_Rank': 23},
 {'ID': 'dai', 'Market_cap_Rank': 25},
 {'ID': 'hedera-hashgraph', 'Market_cap_Rank': 24},
 {'ID': 'paypal-usd', 'Market_cap_Rank': 26},
 {'ID': 'litecoin', 'Market_cap_Rank': 27},
 {'ID': 'zcash', 'Market_cap_Rank': 28},
 {'ID': 'avalanche-2', 'Market_cap_Rank': 29},
 {'ID': 'shiba-inu', 'Market_cap_Rank': 30},
 {'ID': 'sui', 'Market_cap_Rank': 31},
 {'ID': 'the-open-network', 'Market_cap_Rank': 32},
 {'ID': 'world-liberty-financial', 'Market_cap_Rank': 33},
 {'ID': 'crypto-com-chain', 'Market_cap_Rank': 34},
 {'ID': 'tether-gold', 'Market_cap_Rank': 35},
 {'ID': 'memecore', 'Market_cap_Rank': 36},
 {'ID': 'pax-gold', 'Market_cap_Rank': 37},
 {'ID': 'uniswap', 'Market_cap_Rank': 38},
 {'ID': 'polkadot', 'Market_cap_Rank': 39},
 {'ID': 'mantle', 'Market_cap_Rank': 40},
 {'ID': 'blackrock-usd-institutional-digital-liquidity-fund',
  'Market_cap_Rank': 41},
 {'ID': 'aave', 'Market_cap_Rank': 42},
 {'ID': 'falcon-finance', 'Market_cap_Rank': 43},
 {'ID': 'aster-2', 'Market_cap_Rank': 44},
 {'ID': 'bittensor', 'Market_cap_Rank': 45},
 {'ID': 'pepe', 'Market_cap_Rank': 46},
 {'ID': 'global-dollar', 'Market_cap_Rank': 47},
 {'ID': 'hashnote-usyc', 'Market_cap_Rank': 48},
 {'ID': 'okb', 'Market_cap_Rank': 49},
 {'ID': 'ripple-usd', 'Market_cap_Rank': 50},
 {'ID': 'bitget-token', 'Market_cap_Rank': 51},
 {'ID': 'pi-network', 'Market_cap_Rank': 52},
 {'ID': 'sky', 'Market_cap_Rank': 53},
 {'ID': 'htx-dao', 'Market_cap_Rank': 54},
 {'ID': 'ethereum-classic', 'Market_cap_Rank': 55},
 {'ID': 'bfusd', 'Market_cap_Rank': 56},
 {'ID': 'near', 'Market_cap_Rank': 57},
 {'ID': 'ondo-finance', 'Market_cap_Rank': 58},
 {'ID': 'polygon-ecosystem-token', 'Market_cap_Rank': 59},
 {'ID': 'internet-computer', 'Market_cap_Rank': 60},
 {'ID': 'superstate-short-duration-us-government-securities-fund-ustb',
  'Market_cap_Rank': 61},
 {'ID': 'worldcoin-wld', 'Market_cap_Rank': 62},
 {'ID': 'gatechain-token', 'Market_cap_Rank': 63},
 {'ID': 'kucoin-shares', 'Market_cap_Rank': 64},
 {'ID': 'pump-fun', 'Market_cap_Rank': 65},
 {'ID': 'cosmos', 'Market_cap_Rank': 66},
 {'ID': 'midnight-3', 'Market_cap_Rank': 67},
 {'ID': 'hash-2', 'Market_cap_Rank': 68},
 {'ID': 'quant-network', 'Market_cap_Rank': 69},
 {'ID': 'nexo', 'Market_cap_Rank': 70},
 {'ID': 'usdtb', 'Market_cap_Rank': 71},
 {'ID': 'ethena', 'Market_cap_Rank': 72},
 {'ID': 'official-trump', 'Market_cap_Rank': 73},
 {'ID': 'eutbl', 'Market_cap_Rank': 74},
 {'ID': 'flare-networks', 'Market_cap_Rank': 75},
 {'ID': 'kaspa', 'Market_cap_Rank': 76},
 {'ID': 'algorand', 'Market_cap_Rank': 77},
 {'ID': 'pippin', 'Market_cap_Rank': 78},
 {'ID': 'usdd', 'Market_cap_Rank': 79},
 {'ID': 'ousg', 'Market_cap_Rank': 80},
 {'ID': 'render-token', 'Market_cap_Rank': 81},
 {'ID': 'janus-henderson-anemoy-aaa-clo-fund', 'Market_cap_Rank': 82},
 {'ID': 'ondo-us-dollar-yield', 'Market_cap_Rank': 83},
 {'ID': 'filecoin', 'Market_cap_Rank': 84},
 {'ID': 'aptos', 'Market_cap_Rank': 85},
 {'ID': 'xdce-crowd-sale', 'Market_cap_Rank': 86},
 {'ID': 'morpho', 'Market_cap_Rank': 87},
 {'ID': 'vechain', 'Market_cap_Rank': 88},
 {'ID': 'beldex', 'Market_cap_Rank': 89},
 {'ID': 'janus-henderson-anemoy-treasury-fund', 'Market_cap_Rank': 90},
 {'ID': 'usual-usd', 'Market_cap_Rank': 91},
 {'ID': 'arbitrum', 'Market_cap_Rank': 92},
 {'ID': 'gho', 'Market_cap_Rank': 93},
 {'ID': 'stable-2', 'Market_cap_Rank': 95},
 {'ID': 'bonk', 'Market_cap_Rank': 94},
 {'ID': 'a7a5', 'Market_cap_Rank': 96},
 {'ID': 'true-usd', 'Market_cap_Rank': 97},
 {'ID': 'decred', 'Market_cap_Rank': 98},
 {'ID': 'jupiter-exchange-solana', 'Market_cap_Rank': 99},
 {'ID': 'kite-2', 'Market_cap_Rank': 100},
 {'ID': 'fasttoken', 'Market_cap_Rank': 101},
 {'ID': 'usdai', 'Market_cap_Rank': 102},
 {'ID': 'euro-coin', 'Market_cap_Rank': 103},
 {'ID': 'sei-network', 'Market_cap_Rank': 104},
 {'ID': 'blockstack', 'Market_cap_Rank': 105},
 {'ID': 'virtual-protocol', 'Market_cap_Rank': 106},
 {'ID': 'dash', 'Market_cap_Rank': 107},
 {'ID': 'pudgy-penguins', 'Market_cap_Rank': 108},
 {'ID': 'pancakeswap-token', 'Market_cap_Rank': 109},
 {'ID': 'tezos', 'Market_cap_Rank': 110},
 {'ID': 'just', 'Market_cap_Rank': 111},
 {'ID': 'kinesis-gold', 'Market_cap_Rank': 112},
 {'ID': 'first-digital-usd', 'Market_cap_Rank': 113},
 {'ID': 'ether-fi', 'Market_cap_Rank': 114},
 {'ID': 'story-2', 'Market_cap_Rank': 115},
 {'ID': 'curve-dao-token', 'Market_cap_Rank': 117},
 {'ID': 'fetch-ai', 'Market_cap_Rank': 116},
 {'ID': 'c8ntinuum', 'Market_cap_Rank': 118},
 {'ID': 'lighter', 'Market_cap_Rank': 119},
 {'ID': 'chiliz', 'Market_cap_Rank': 120},
 {'ID': 'hastra-prime', 'Market_cap_Rank': 121},
 {'ID': 'usx', 'Market_cap_Rank': 122},
 {'ID': 'apenft', 'Market_cap_Rank': 123},
 {'ID': 'gnosis', 'Market_cap_Rank': 124},
 {'ID': 'bittorrent', 'Market_cap_Rank': 125},
 {'ID': 'bitcoin-cash-sv', 'Market_cap_Rank': 126},
 {'ID': 'kaia', 'Market_cap_Rank': 127},
 {'ID': 'sun-token', 'Market_cap_Rank': 128},
 {'ID': 'injective-protocol', 'Market_cap_Rank': 129},
 {'ID': 'adi-token', 'Market_cap_Rank': 130},
 {'ID': 'aerodrome-finance', 'Market_cap_Rank': 131},
 {'ID': 'layerzero', 'Market_cap_Rank': 132},
 {'ID': 'pyth-network', 'Market_cap_Rank': 133},
 {'ID': 'iota', 'Market_cap_Rank': 134},
 {'ID': 'crvusd', 'Market_cap_Rank': 135},
 {'ID': 'jasmycoin', 'Market_cap_Rank': 136},
 {'ID': 'the-graph', 'Market_cap_Rank': 137},
 {'ID': 'celestia', 'Market_cap_Rank': 138},
 {'ID': 'floki', 'Market_cap_Rank': 140},
 {'ID': 'spx6900', 'Market_cap_Rank': 139},
 {'ID': 'frax', 'Market_cap_Rank': 141},
 {'ID': 'siren-2', 'Market_cap_Rank': 142},
 {'ID': 'olympus', 'Market_cap_Rank': 143},
 {'ID': 'syrup', 'Market_cap_Rank': 144},
 {'ID': 'btse-token', 'Market_cap_Rank': 145},
 {'ID': 'doublezero', 'Market_cap_Rank': 146},
 {'ID': 'lido-dao', 'Market_cap_Rank': 147},
 {'ID': 'conflux-token', 'Market_cap_Rank': 148},
 {'ID': 'helium', 'Market_cap_Rank': 149},
 {'ID': 'optimism', 'Market_cap_Rank': 150},
 {'ID': 'humanity', 'Market_cap_Rank': 151},
 {'ID': 'newton-project', 'Market_cap_Rank': 152},
 {'ID': 'telcoin', 'Market_cap_Rank': 153},
 {'ID': 'ethereum-name-service', 'Market_cap_Rank': 154},
 {'ID': 'nusd-2', 'Market_cap_Rank': 155},
 {'ID': 'starknet', 'Market_cap_Rank': 156},
 {'ID': 'axie-infinity', 'Market_cap_Rank': 157},
 {'ID': 'ylds', 'Market_cap_Rank': 158},
 {'ID': 'monad', 'Market_cap_Rank': 159},
 {'ID': 'undeads-games', 'Market_cap_Rank': 160},
 {'ID': 'usda-2', 'Market_cap_Rank': 161},
 {'ID': 'spiko-us-t-bills-money-market-fund', 'Market_cap_Rank': 162},
 {'ID': 'agora-dollar', 'Market_cap_Rank': 163},
 {'ID': 'the-sandbox', 'Market_cap_Rank': 164},
 {'ID': 'trust-wallet-token', 'Market_cap_Rank': 165},
 {'ID': 'pendle', 'Market_cap_Rank': 166},
 {'ID': 'blockchain-capital', 'Market_cap_Rank': 167},
 {'ID': 'zebec-network', 'Market_cap_Rank': 168},
 {'ID': 'flying-tulip', 'Market_cap_Rank': 169},
 {'ID': 'ape-and-pepe', 'Market_cap_Rank': 170},
 {'ID': 'plasma', 'Market_cap_Rank': 171},
 {'ID': 'dogwifcoin', 'Market_cap_Rank': 172},
 {'ID': 'ultima', 'Market_cap_Rank': 173},
 {'ID': 'swissborg', 'Market_cap_Rank': 174},
 {'ID': 'terra-luna', 'Market_cap_Rank': 175},
 {'ID': 'vision-3', 'Market_cap_Rank': 176},
 {'ID': 'tradable-na-rent-financing-platform-sstn', 'Market_cap_Rank': 177},
 {'ID': 'neo', 'Market_cap_Rank': 178},
 {'ID': 'river', 'Market_cap_Rank': 179},
 {'ID': 'theta-token', 'Market_cap_Rank': 180},
 {'ID': 'zksync', 'Market_cap_Rank': 181},
 {'ID': 'falcon-finance-ff', 'Market_cap_Rank': 182},
 {'ID': 'basic-attention-token', 'Market_cap_Rank': 183},
 {'ID': 'chain-2', 'Market_cap_Rank': 184},
 {'ID': 'decentraland', 'Market_cap_Rank': 185},
 {'ID': 'fidelity-digital-interest-token', 'Market_cap_Rank': 186},
 {'ID': 'venice-token', 'Market_cap_Rank': 188},
 {'ID': 'ribbita-by-virtuals', 'Market_cap_Rank': 187},
 {'ID': 'compound-governance-token', 'Market_cap_Rank': 189},
 {'ID': 'lombard-protocol', 'Market_cap_Rank': 190},
 {'ID': 'infinifi-usd', 'Market_cap_Rank': 191},
 {'ID': 'sentient', 'Market_cap_Rank': 192},
 {'ID': 'convex-finance', 'Market_cap_Rank': 193},
 {'ID': 'wefi', 'Market_cap_Rank': 194},
 {'ID': 'gala', 'Market_cap_Rank': 195},
 {'ID': 'the9bit', 'Market_cap_Rank': 196},
 {'ID': 'mx-token', 'Market_cap_Rank': 197},
 {'ID': 'raydium', 'Market_cap_Rank': 198},
 {'ID': 'bnb48-club-token', 'Market_cap_Rank': 199},
 {'ID': 'reallink', 'Market_cap_Rank': 200},
 {'ID': 'instadapp', 'Market_cap_Rank': 201},
 {'ID': 'satoshi-stablecoin', 'Market_cap_Rank': 203},
 {'ID': 'dexe', 'Market_cap_Rank': 202},
 {'ID': 'stasis-eurs', 'Market_cap_Rank': 204},
 {'ID': 'fartcoin', 'Market_cap_Rank': 205},
 {'ID': 'power-protocol', 'Market_cap_Rank': 206},
 {'ID': 'ecash', 'Market_cap_Rank': 207},
 {'ID': 'sonic-3', 'Market_cap_Rank': 208},
 {'ID': 'astherus-usdf', 'Market_cap_Rank': 209},
 {'ID': 'gusd', 'Market_cap_Rank': 210},
 {'ID': 'golem', 'Market_cap_Rank': 211},
 {'ID': 'theo-short-duration-us-treasury-fund', 'Market_cap_Rank': 212},
 {'ID': 'immutable-x', 'Market_cap_Rank': 213},
 {'ID': 'wemix-token', 'Market_cap_Rank': 214},
 {'ID': 'thorchain', 'Market_cap_Rank': 215},
 {'ID': 'origintrail', 'Market_cap_Rank': 216},
 {'ID': 'zero-gravity', 'Market_cap_Rank': 217},
 {'ID': 'rollbit-coin', 'Market_cap_Rank': 218},
 {'ID': 'seeker', 'Market_cap_Rank': 221},
 {'ID': 'berachain-bera', 'Market_cap_Rank': 219},
 {'ID': 'vaulta', 'Market_cap_Rank': 222},
 {'ID': 'apollo-diversified-credit-securitize-fund', 'Market_cap_Rank': 220},
 {'ID': 'elrond-erd-2', 'Market_cap_Rank': 223},
 {'ID': 'gmt-token', 'Market_cap_Rank': 224},
 {'ID': 'jito-governance-token', 'Market_cap_Rank': 225},
 {'ID': 'coco-2', 'Market_cap_Rank': 226},
 {'ID': 'safepal', 'Market_cap_Rank': 227},
 {'ID': '1inch', 'Market_cap_Rank': 228},
 {'ID': 'havven', 'Market_cap_Rank': 229},
 {'ID': 'build-on', 'Market_cap_Rank': 230},
 {'ID': 'ozone-chain', 'Market_cap_Rank': 231},
 {'ID': 'keeta', 'Market_cap_Rank': 232},
 {'ID': 'amp-token', 'Market_cap_Rank': 233},
 {'ID': 'zano', 'Market_cap_Rank': 234},
 {'ID': 'cow-protocol', 'Market_cap_Rank': 235},
 {'ID': 'ai-rig-complex', 'Market_cap_Rank': 236},
 {'ID': 'dola-usd', 'Market_cap_Rank': 237},
 {'ID': 'walrus-2', 'Market_cap_Rank': 238},
 {'ID': 'loaded-lions', 'Market_cap_Rank': 240},
 {'ID': 'pleasing-usd', 'Market_cap_Rank': 241},
 {'ID': 'comedian', 'Market_cap_Rank': 242},
 {'ID': 'cap-usd', 'Market_cap_Rank': 243},
 {'ID': 'livepeer', 'Market_cap_Rank': 245},
 {'ID': 'cash-4', 'Market_cap_Rank': 244},
 {'ID': 'mimblewimblecoin', 'Market_cap_Rank': 251},
 {'ID': 'arweave', 'Market_cap_Rank': 239},
 {'ID': 'eigenlayer', 'Market_cap_Rank': 246},
 {'ID': 'quantum-resistant-ledger', 'Market_cap_Rank': 247},
 {'ID': 're-protocol-reusd', 'Market_cap_Rank': 248},
 {'ID': 'frax-usd', 'Market_cap_Rank': 249}]

In [9]:
import pandas as pd
df=pd.DataFrame(records)
df

                           ID  Market_cap_Rank
0                     bitcoin                1
1                    ethereum                2
2                      tether                3
3                      ripple                4
4                 binancecoin                5
..                        ...              ...
245                   arweave              239
246                eigenlayer              246
247  quantum-resistant-ledger              247
248         re-protocol-reusd              248
249                  frax-usd              249

[250 rows x 2 columns]

In [10]:
import pandas as pd
# 1. Create a pandas DataFrame named coins_df from the Records list.
coins_df = pd.DataFrame(Records)

# 2. Convert the Last_update column in coins_df to datetime objects.
coins_df['Last_update'] = pd.to_datetime(coins_df['Last_update'])

# 3. Extract only the date part from the Last_update column and assign it to a new column named Date in coins_df.
coins_df['date'] = coins_df['Last_update'].dt.date

# 4. Drop the original Last_update column from coins_df.
coins_df = coins_df.drop('Last_update', axis=1)

# 5. Rename the Id column in coins_df to id to match the database schema.
coins_df = coins_df.rename(columns={'Id': 'id'})

print("DataFrame 'coins_df' prepared for database insertion:")
coins_df.head()

DataFrame 'coins_df' prepared for database insertion:

,ID,symbol,Name,current_price,Market_cap,Market_cap_Rank,Total_volume,Circulating_Supply,Total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,65241.000000,1305769714138,1,[total_volume],1.999438e+07,1.999450e+07,126080.00,67.810000,2026-02-25
1,ethereum,eth,Ethereum,1915.250000,231249290227,2,[total_volume],1.206923e+08,1.206923e+08,4946.05,0.432979,2026-02-25
2,tether,usdt,Tether,0.999818,183589915324,3,[total_volume],1.836242e+11,1.890912e+11,1.32,0.572521,2026-02-25
3,ripple,xrp,XRP,1.380000,83921821776,4,[total_volume],6.101858e+10,9.998571e+10,3.65,0.002686,2026-02-25
4,binancecoin,bnb,BNB,602.540000,82128547665,5,[total_volume],1.363589e+08,1.363589e+08,1369.99,0.039818,2026-02-25

# Top 3 Cryptocurrency

In [11]:
import requests
coin_id='bitcoin'
url=f'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365'
response=requests.get(url)

response.json()#pandas datetimeand convert milliseconds into date

{'prices': [[1740528000000, 7729282.415455005],
  [1740614400000, 7314307.147526646],
  [1740700800000, 7397416.663356487],
  [1740787200000, 7386259.847331922],
  [1740873600000, 7523008.862171689],
  [1740960000000, 8244472.61232367],
  [1741046400000, 7521257.854514662],
  [1741132800000, 7615008.334491884],
  [1741219200000, 7869430.047939962],
  [1741305600000, 7841736.557001183],
  [1741392000000, 7562231.150267524],
  [1741478400000, 7503958.351863089],
  [1741564800000, 7035607.792612969],
  [1741651200000, 6882112.04135304],
  [1741737600000, 7220111.199834512],
  [1741824000000, 7311397.167011021],
  [1741910400000, 7049331.751158462],
  [1741996800000, 7301205.756783538],
  [1742083200000, 7337203.4861049205],
  [1742169600000, 7182714.546311197],
  [1742256000000, 7307625.213417549],
  [1742342400000, 7166130.900539224],
  [1742428800000, 7495414.341859128],
  [1742515200000, 7275140.94449613],
  [1742601600000, 7224000.906005809],
  [1742688000000, 7205763.671408613],
  [1742774400000, 7377568.408827406],
  [1742860800000, 7471026.999919416],
  [1742947200000, 7490943.665690553],
  [1743033600000, 7448415.462567322],
  [1743120000000, 7474953.075439318],
  [1743206400000, 7216289.858225705],
  [1743292800000, 7072289.607125187],
  [1743379200000, 7044678.366106417],
  [1743465600000, 7049110.1215911815],
  [1743552000000, 7295181.762562074],
  [1743638400000, 7072204.244187081],
  [1743724800000, 7092361.1660758825],
  [1743811200000, 7177434.935222951],
  [1743897600000, 7149914.289024058],
  [1743984000000, 6689389.08502666],
  [1744070400000, 6810911.664670934],
  [1744156800000, 6597493.475585312],
  [1744243200000, 7122745.761241968],
  [1744329600000, 6866025.560636041],
  [1744416000000, 7182775.418149425],
  [1744502400000, 7333947.924555619],
  [1744588800000, 7187425.846627208],
  [1744675200000, 7271599.950976666],
  [1744761600000, 7171572.949306771],
  [1744848000000, 7201187.29755112],
  [1744934400000, 7251703.328254263],
  [1745020800000, 7209254.173849113],
  [1745107200000, 7268417.49030321],
  [1745193600000, 7263849.726468839],
  [1745280000000, 7447341.987486609],
  [1745366400000, 7975735.892697773],
  [1745452800000, 8003280.21321444],
  [1745539200000, 8000169.783417303],
  [1745625600000, 8092178.475391482],
  [1745712000000, 8081159.94608841],
  [1745798400000, 8009924.38113424],
  [1745884800000, 8092853.390805625],
  [1745971200000, 8027696.597798843],
  [1746057600000, 7968688.759781316],
  [1746144000000, 8167058.515487802],
  [1746230400000, 8196935.158997864],
  [1746316800000, 8118000.316161074],
  [1746403200000, 7973099.086450076],
  [1746489600000, 7980688.008703099],
  [1746576000000, 8207545.052481962],
  [1746662400000, 8229539.783984127],
  [1746748800000, 8868161.595114123],
  [1746835200000, 8794022.755272726],
  [1746921600000, 8936515.44901635],
  [1747008000000, 8882429.185761888],
  [1747094400000, 8739740.641206343],
  [1747180800000, 8860925.91388854],
  [1747267200000, 8854656.259617174],
  [1747353600000, 8861418.050018335],
  [1747440000000, 8862661.820151662],
  [1747526400000, 8833249.416670207],
  [1747612800000, 9065676.354329923],
  [1747699200000, 9017978.28123392],
  [1747785600000, 9134061.037906067],
  [1747872000000, 9387459.456660772],
  [1747958400000, 9591418.421810476],
  [1748044800000, 9121570.655984685],
  [1748131200000, 9173866.493436038],
  [1748217600000, 9274975.732278159],
  [1748304000000, 9314436.685236426],
  [1748390400000, 9310175.102671716],
  [1748476800000, 9208280.990679564],
  [1748563200000, 9026592.666677358],
  [1748649600000, 8900073.972215421],
  [1748736000000, 8957968.682594351],
  [1748822400000, 9040802.274014382],
  [1748908800000, 9038740.617012177],
  [1748995200000, 9036688.899610182],
  [1749081600000, 9003749.459208991],
  [1749168000000, 8729536.730077919],
  [1749254400000, 8957197.574287502],
  [1749340800000, 9066295.741750069],
  [1749427200000, 9066867.46885247],
  [1749513600000, 9455619.179043707],
  [1749600000000, 9440056.689266069],
  [1749686400000, 9288882.88186932],
  [1749772800000, 9081227.025134273],
  [1749859200000, 9132702.543985052],
  [1749945600000, 9084246.101299008],
  [1750032000000, 9090411.27477335],
  [1750118400000, 9208980.453923177],
  [1750204800000, 9039952.955659283],
  [1750291200000, 9070436.848135183],
  [1750377600000, 9080584.318377115],
  [1750464000000, 8945088.576284403],
  [1750550400000, 8792883.07729243],
  [1750636800000, 8731873.284684414],
  [1750723200000, 9111429.945371069],
  [1750809600000, 9111165.38661966],
  [1750896000000, 9223086.808659252],
  [1750982400000, 9165684.099752242],
  [1751068800000, 9156217.740562832],
  [1751155200000, 9177823.305095606],
  [1751241600000, 9263092.465181679],
  [1751328000000, 9181709.414667957],
  [1751414400000, 9054321.250569785],
  [1751500800000, 9325640.339018358],
  [1751587200000, 9360532.463404836],
  [1751673600000, 9250500.062624797],
  [1751760000000, 9285248.177863376],
  [1751846400000, 9337523.923073687],
  [1751932800000, 9302203.177316865],
  [1752019200000, 9338122.035800587],
  [1752105600000, 9541743.483380785],
  [1752192000000, 9934947.612549465],
  [1752278400000, 10091339.413757524],
  [1752364800000, 10078287.164944079],
  [1752451200000, 10222853.345055208],
  [1752537600000, 10301939.218478084],
  [1752624000000, 10119542.204331392],
  [1752710400000, 10198739.393321177],
  [1752796800000, 10277885.47839658],
  [1752883200000, 10164069.670952292],
  [1752969600000, 10156547.547410768],
  [1753056000000, 10101549.352407157],
  [1753142400000, 10136533.758092493],
  [1753228800000, 10357349.26643955],
  [1753315200000, 10249425.74900696],
  [1753401600000, 10229427.683390176],
  [1753488000000, 10168020.4311719],
  [1753574400000, 10203795.311577797],
  [1753660800000, 10330494.375551593],
  [1753747200000, 10240072.841855934],
  [1753833600000, 10260715.669243045],
  [1753920000000, 10330510.927890545],
  [1754006400000, 10122552.718401065],
  [1754092800000, 9870309.502282668],
  [1754179200000, 9811174.470132805],
  [1754265600000, 9963363.104407016],
  [1754352000000, 10119947.866363142],
  [1754438400000, 10011721.5506572],
  [1754524800000, 10094655.435390146],
  [1754611200000, 10270107.263258504],
  [1754697600000, 10236807.855788205],
  [1754784000000, 10220759.730383817],
  [1754870400000, 10434491.300112702],
  [1754956800000, 10412275.449238887],
  [1755043200000, 10529495.638104321],
  [1755129600000, 10805439.78369676],
  [1755216000000, 10383230.847886154],
  [1755302400000, 10268856.947554458],
  [1755388800000, 10282983.838569582],
  [1755475200000, 10286533.101169772],
  [1755561600000, 10148644.242275473],
  [1755648000000, 9819786.419050021],
  [1755734400000, 9942066.543754837],
  [1755820800000, 9813063.27750558],
  [1755907200000, 10203164.21582744],
  [1755993600000, 10074416.19618185],
  [1756080000000, 9903221.35080575],
  [1756166400000, 9653212.189243559],
  [1756252800000, 9801777.668906499],
  [1756339200000, 9749130.25886824],
  [1756425600000, 9856302.06893481],
  [1756512000000, 9564432.013993934],
  [1756598400000, 9591794.692119835],
  [1756684800000, 9545191.818462053],
  [1756771200000, 9606486.0790093],
  [1756857600000, 9784574.242949013],
  [1756944000000, 9838796.609221794],
  [1757030400000, 9765163.284050079],
  [1757116800000, 9759026.631183332],
  [1757203200000, 9718962.630296323],
  [1757289600000, 9800346.003033817],
  [1757376000000, 9856054.84901548],
  [1757462400000, 9840553.151484529],
  [1757548800000, 10035954.764445597],
  [1757635200000, 10195205.098488238],
  [1757721600000, 10254357.380846838],
  [1757808000000, 10237593.3071353],
  [1757894400000, 10184894.127284445],
  [1757980800000, 10169238.650025213],
  [1758067200000, 10261685.530263504],
  [1758153600000, 10237752.888404036],
  [1758240000000, 10333070.25718556],
  [1758326400000, 10189201.725638028],
  [1758412800000, 10194461.688819751],
  [1758499200000, 10158260.693491202],
  [1758585600000, 9951646.271657305],
  [1758672000000, 9948492.512889242],
  [1758758400000, 10060469.351465985],
  [1758844800000, 9673068.167457229],
  [1758931200000, 9728251.057537576],
  [1759017600000, 9723915.967631772],
  [1759104000000, 9944472.608696878],
  [1759190400000, 10139763.924082505],
  [1759276800000, 10130020.723922314],
  [1759363200000, 10509252.859358784],
  [1759449600000, 10700725.995237181],
  [1759536000000, 10847910.013598107],
  [1759622400000, 10859533.642673422],
  [1759708800000, 10959365.064936124],
  [1759795200000, 11070472.246732509],
  [1759881600000, 10783920.730192943],
  [1759968000000, 10949945.97908964],
  [1760054400000, 10814774.599012492],
  [1760140800000, 10047260.111235712],
  [1760227200000, 9838358.210748602],
  [1760313600000, 10223942.881584922],
  [1760400000000, 10216224.051870666],
  [1760486400000, 10046351.075825775],
  [1760572800000, 9721344.884648668],
  [1760659200000, 9509774.024195194],
  [1760745600000, 9369768.130232994],
  [1760832000000, 9432476.848616607],
  [1760918400000, 9558930.877185136],
  [1761004800000, 9720308.914971137],
  [1761091200000, 9549158.301143315],
  [1761177600000, 9442499.946295625],
  [1761264000000, 9659976.397607893],
  [1761350400000, 9747832.72977752],
  [1761436800000, 9802501.15016422],
  [1761523200000, 10055171.794296525],
  [1761609600000, 10073474.454011032],
  [1761696000000, 9965129.220872145],
  [1761782400000, 9722166.86543983],
  [1761868800000, 9593893.17104472],
  [1761955200000, 9734748.91964181],
  [1762041600000, 9765788.362963019],
  [1762128000000, 9824421.072227614],
  [1762214400000, 9450928.858755054],
  [1762300800000, 9018317.599498693],
  [1762387200000, 9199126.082980732],
  [1762473600000, 8984607.813501872],
  [1762560000000, 9167651.236387476],
  [1762646400000, 9069592.039128657],
  [1762732800000, 9283589.00601575],
  [1762819200000, 9394913.182233905],
  [1762905600000, 9108594.696793688],
  [1762992000000, 8994239.327086337],
  [1763078400000, 8857694.85444411],
  [1763164800000, 8376936.116014769],
  [1763251200000, 8470582.749251666],
  [1763337600000, 8373085.239387692],
  [1763424000000, 8157780.455111292],
  [1763510400000, 8219844.429070548],
  [1763596800000, 8084502.70583037],
  [1763683200000, 7685198.360480496],
  [1763769600000, 7622398.708162882],
  [1763856000000, 7591078.566298594],
  [1763942400000, 7778520.446850556],
  [1764028800000, 7865475.253834086],
  [1764115200000, 7783791.323601658],
  [1764201600000, 8066930.863801428],
  [1764288000000, 8157156.351483771],
  [1764374400000, 8126220.637986011],
  [1764460800000, 8116488.479072998],
  [1764547200000, 8078246.317717989],
  [1764633600000, 7731939.31508293],
  [1764720000000, 8213485.439946512],
  [1764806400000, 8441734.894689914],
  [1764892800000, 8277612.193785475],
  [1764979200000, 8033337.656068311],
  [1765065600000, 8028324.929700683],
  [1765152000000, 8110183.521497487],
  [1765238400000, 8167418.75650716],
  [1765324800000, 8337407.11660591],
  [1765411200000, 8261440.281355997],
  [1765497600000, 8347818.307928058],
  [1765584000000, 8175319.49414227],
  [1765670400000, 8175924.735194205],
  [1765756800000, 7992348.231966222],
  [1765843200000, 7844409.288926788],
  [1765929600000, 7987315.985984798],
  [1766016000000, 7781471.915537124],
  [1766102400000, 7712879.171308659],
  [1766188800000, 7892110.371399885],
  [1766275200000, 7913974.621357582],
  [1766361600000, 7933999.65474005],
  [1766448000000, 7929162.75966298],
  [1766534400000, 7820620.968822208],
  [1766620800000, 7872946.774052088],
  [1766707200000, 7860175.221034703],
  [1766793600000, 7838865.798860937],
  [1766880000000, 7886342.002067149],
  [1766966400000, 7887770.596681177],
  [1767052800000, 7835388.056690424],
  [1767139200000, 7936951.056508718],
  [1767225600000, 7875103.91153735],
  [1767312000000, 7982611.090931888],
  [1767398400000, 8094664.567193232],
  [1767484800000, 8154755.980058913],
  [1767571200000, 8224912.970329631],
  [1767657600000, 8475311.204337161],
  [1767744000000, 8443838.294347357],
  [1767830400000, 8200790.873528976],
  [1767916800000, 8179932.125614385],
  [1768003200000, 8169727.593041189],
  [1768089600000, 8164051.8328820085],
  [1768176000000, 8196362.9552232],
  [1768262400000, 8214254.506811856],
  [1768348800000, 8600260.479528198],
  [1768435200000, 8754772.557780331],
  [1768521600000, 8637202.771129187],
  [1768608000000, 8665871.041073622],
  [1768694400000, 8641731.269593248],
  [1768780800000, 8504968.615885023],
  [1768867200000, 8414003.970645163],
  [1768953600000, 8046939.8302773405],
  [1769040000000, 8179241.969294843],
  [1769126400000, 8189307.776814618],
  [1769212800000, 8190756.883147298],
  [1769299200000, 8167427.829795334],
  [1769385600000, 7931480.8104405],
  [1769472000000, 8098992.121060789],
  [1769558400000, 8165356.488930265],
  [1769644800000, 8206661.924142179],
  [1769731200000, 7762053.970031044],
  [1769817600000, 7714332.820802952],
  [1769904000000, 7217787.461780625],
  [1769990400000, 7055170.4747747015],
  [1770076800000, 7124353.514366637],
  [1770163200000, 6839512.652076184],
  [1770249600000, 6617843.606631121],
  [1770336000000, 5676634.189757013],
  [1770422400000, 6389223.0613750955],
  [1770508800000, 6278047.808376017],
  [1770595200000, 6388983.809905373],
  [1770681600000, 6363124.007122537],
  [1770768000000, 6230645.199778009],
  [1770854400000, 6073656.888033923],
  [1770940800000, 5993963.2553228345],
  [1771027200000, 6234117.350281114],
  [1771113600000, 6317657.207954805],
  [1771200000000, 6222983.54818252],
  [1771286400000, 6255749.578602175],
  [1771372800000, 6116329.755578176],
  [1771459200000, 6033801.7653913135],
  [1771545600000, 6092367.347486159],
  [1771632000000, 6166730.671036533],
  [1771718400000, 6167421.5569663085],
  [1771804800000, 6132044.38390857],
  [1771891200000, 5877904.816486458],
  [1771977600000, 5825506.041087636],
  [1772018280000, 5931411.726088468]],
 'market_caps': [[1740528000000, 153247587387219.9],
  [1740614400000, 145092897422240.22],
  [1740700800000, 146670947325212.53],
  [1740787200000, 146493284420451.72],
  [1740873600000, 149188251730084.6],
  [1740960000000, 163410530927229.25],
  [1741046400000, 149181798210246.72],
  [1741132800000, 151011753968614.66],
  [1741219200000, 156140079921156.88],
  [1741305600000, 155332618990098.5],
  [1741392000000, 149934788269021.75],
  [1741478400000, 148837480868612.94],
  [1741564800000, 139583949185400.2],
  [1741651200000, 136582014886006.11],
  [1741737600000, 143269950032252.84],
  [1741824000000, 144904649435288.6],
  [1741910400000, 139813920027311.94],
  [1741996800000, 144832172272915.2],
  [1742083200000, 145556393063008.88],
  [1742169600000, 142477016504235.94],
  [1742256000000, 144960350656778.97],
  [1742342400000, 142195295862922.2],
  [1742428800000, 148635356385415.66],
  [1742515200000, 144391367721865.88],
  [1742601600000, 143324180216465.75],
  [1742688000000, 142972251116074.03],
  [1742774400000, 146369361522808.2],
  [1742860800000, 148236568994576.1],
  [1742947200000, 148531315670993.2],
  [1743033600000, 147738113790149.78],
  [1743120000000, 148250573414973.28],
  [1743206400000, 143127644099250.1],
  [1743292800000, 140340804500989.94],
  [1743379200000, 139770328164058.75],
  [1743465600000, 139683227029930.31],
  [1743552000000, 144692611411592.8],
  [1743638400000, 140315492944612.62],
  [1743724800000, 140931082892341.03],
  [1743811200000, 142452612689242.22],
  [1743897600000, 141638568405765.44],
  [1743984000000, 133026191892504.16],
  [1744070400000, 136030860146543.77],
  [1744156800000, 130952471210149.42],
  [1744243200000, 141431144678745.16],
  [1744329600000, 136293671033013.61],
  [1744416000000, 142543573292291.38],
  [1744502400000, 145604183184316.78],
  [1744588800000, 142622853806903.7],
  [1744675200000, 144345816768012.4],
  [1744761600000, 142370094856537.44],
  [1744848000000, 143029004221568.34],
  [1744934400000, 143976048009443.06],
  [1745020800000, 143134711526525.56],
  [1745107200000, 144305951874866.28],
  [1745193600000, 144213572928166.12],
  [1745280000000, 147811055811997.84],
  [1745366400000, 158412191601745.1],
  [1745452800000, 158915548781568.0],
  [1745539200000, 158882010025594.88],
  [1745625600000, 160704481873690.8],
  [1745712000000, 160449211873569.97],
  [1745798400000, 159053087736354.47],
  [1745884800000, 160703590988217.25],
  [1745971200000, 159335269302606.8],
  [1746057600000, 158243639764679.06],
  [1746144000000, 162184675927639.97],
  [1746230400000, 162765758571135.0],
  [1746316800000, 161212206683015.7],
  [1746403200000, 158302280917006.22],
  [1746489600000, 158547084714911.78],
  [1746576000000, 163011406532277.9],
  [1746662400000, 163454639004415.8],
  [1746748800000, 176189564081226.4],
  [1746835200000, 174667261488634.56],
  [1746921600000, 177407732339299.34],
  [1747008000000, 176433904354746.88],
  [1747094400000, 173674333299646.56],
  [1747180800000, 175999429237788.7],
  [1747267200000, 175888780326749.9],
  [1747353600000, 176029183872811.16],
  [1747440000000, 176106843788904.56],
  [1747526400000, 175472918502628.47],
  [1747612800000, 179969199355517.6],
  [1747699200000, 179155548290416.03],
  [1747785600000, 181486652295308.97],
  [1747872000000, 186509837960828.16],
  [1747958400000, 190410208940880.75],
  [1748044800000, 181347759081015.84],
  [1748131200000, 182278846776151.78],
  [1748217600000, 184292802432865.47],
  [1748304000000, 185054409080508.47],
  [1748390400000, 185024049829002.9],
  [1748476800000, 183019605072651.28],
  [1748563200000, 179374386620553.34],
  [1748649600000, 176855933911134.62],
  [1748736000000, 178022821809896.6],
  [1748822400000, 179702340560357.03],
  [1748908800000, 179629331590192.03],
  [1748995200000, 179585658320534.6],
  [1749081600000, 178948840966760.94],
  [1749168000000, 173498311645619.7],
  [1749254400000, 178027023469230.2],
  [1749340800000, 180204160164195.62],
  [1749427200000, 180205822652402.1],
  [1749513600000, 187967193249811.56],
  [1749600000000, 187524509763221.47],
  [1749686400000, 184575081521565.3],
  [1749772800000, 180624143535765.12],
  [1749859200000, 181539805900760.34],
  [1749945600000, 180636698742719.03],
  [1750032000000, 180723901772300.84],
  [1750118400000, 183221269148744.34],
  [1750204800000, 179702316313150.78],
  [1750291200000, 180302143667231.16],
  [1750377600000, 180531137316963.9],
  [1750464000000, 177890103970304.6],
  [1750550400000, 174711454616211.44],
  [1750636800000, 173609591377867.56],
  [1750723200000, 181149919791061.84],
  [1750809600000, 181156284017729.62],
  [1750896000000, 183375534968167.0],
  [1750982400000, 182252346979144.12],
  [1751068800000, 182050553824902.0],
  [1751155200000, 182496862611105.2],
  [1751241600000, 184172362843128.75],
  [1751328000000, 182589937080075.4],
  [1751414400000, 180042186852721.9],
  [1751500800000, 185433877443111.84],
  [1751587200000, 186153377423026.12],
  [1751673600000, 183964052155743.7],
  [1751760000000, 184674889643392.38],
  [1751846400000, 185655570923395.9],
  [1751932800000, 184993020620040.47],
  [1752019200000, 185732711341357.97],
  [1752105600000, 189862956245589.16],
  [1752192000000, 197472885391991.06],
  [1752278400000, 200727427668076.25],
  [1752364800000, 200459098474667.5],
  [1752451200000, 203315574509896.47],
  [1752537600000, 204934287036692.16],
  [1752624000000, 201329642820657.56],
  [1752710400000, 202964035111987.44],
  [1752796800000, 204467504015373.97],
  [1752883200000, 202194802954273.38],
  [1752969600000, 202042587795977.12],
  [1753056000000, 201050515863258.1],
  [1753142400000, 201670805141508.38],
  [1753228800000, 206145479119255.44],
  [1753315200000, 203895633737564.28],
  [1753401600000, 203523367873936.34],
  [1753488000000, 202325740297391.03],
  [1753574400000, 203017861799776.94],
  [1753660800000, 205584489488322.06],
  [1753747200000, 203882439269756.53],
  [1753833600000, 204174804126429.94],
  [1753920000000, 205475160109208.53],

In [12]:
import pandas as pd
coin_id='Ethereum'
url=f'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365'
response=requests.get(url)

response.json()#pandas datetimeand convert milliseconds into date

{'prices': [[1740528000000, 7729282.415455005],
  [1740614400000, 7314307.147526646],
  [1740700800000, 7397416.663356487],
  [1740787200000, 7386259.847331922],
  [1740873600000, 7523008.862171689],
  [1740960000000, 8244472.61232367],
  [1741046400000, 7521257.854514662],
  [1741132800000, 7615008.334491884],
  [1741219200000, 7869430.047939962],
  [1741305600000, 7841736.557001183],
  [1741392000000, 7562231.150267524],
  [1741478400000, 7503958.351863089],
  [1741564800000, 7035607.792612969],
  [1741651200000, 6882112.04135304],
  [1741737600000, 7220111.199834512],
  [1741824000000, 7311397.167011021],
  [1741910400000, 7049331.751158462],
  [1741996800000, 7301205.756783538],
  [1742083200000, 7337203.4861049205],
  [1742169600000, 7182714.546311197],
  [1742256000000, 7307625.213417549],
  [1742342400000, 7166130.900539224],
  [1742428800000, 7495414.341859128],
  [1742515200000, 7275140.94449613],
  [1742601600000, 7224000.906005809],
  [1742688000000, 7205763.671408613],
  [1742774400000, 7377568.408827406],
  [1742860800000, 7471026.999919416],
  [1742947200000, 7490943.665690553],
  [1743033600000, 7448415.462567322],
  [1743120000000, 7474953.075439318],
  [1743206400000, 7216289.858225705],
  [1743292800000, 7072289.607125187],
  [1743379200000, 7044678.366106417],
  [1743465600000, 7049110.1215911815],
  [1743552000000, 7295181.762562074],
  [1743638400000, 7072204.244187081],
  [1743724800000, 7092361.1660758825],
  [1743811200000, 7177434.935222951],
  [1743897600000, 7149914.289024058],
  [1743984000000, 6689389.08502666],
  [1744070400000, 6810911.664670934],
  [1744156800000, 6597493.475585312],
  [1744243200000, 7122745.761241968],
  [1744329600000, 6866025.560636041],
  [1744416000000, 7182775.418149425],
  [1744502400000, 7333947.924555619],
  [1744588800000, 7187425.846627208],
  [1744675200000, 7271599.950976666],
  [1744761600000, 7171572.949306771],
  [1744848000000, 7201187.29755112],
  [1744934400000, 7251703.328254263],
  [1745020800000, 7209254.173849113],
  [1745107200000, 7268417.49030321],
  [1745193600000, 7263849.726468839],
  [1745280000000, 7447341.987486609],
  [1745366400000, 7975735.892697773],
  [1745452800000, 8003280.21321444],
  [1745539200000, 8000169.783417303],
  [1745625600000, 8092178.475391482],
  [1745712000000, 8081159.94608841],
  [1745798400000, 8009924.38113424],
  [1745884800000, 8092853.390805625],
  [1745971200000, 8027696.597798843],
  [1746057600000, 7968688.759781316],
  [1746144000000, 8167058.515487802],
  [1746230400000, 8196935.158997864],
  [1746316800000, 8118000.316161074],
  [1746403200000, 7973099.086450076],
  [1746489600000, 7980688.008703099],
  [1746576000000, 8207545.052481962],
  [1746662400000, 8229539.783984127],
  [1746748800000, 8868161.595114123],
  [1746835200000, 8794022.755272726],
  [1746921600000, 8936515.44901635],
  [1747008000000, 8882429.185761888],
  [1747094400000, 8739740.641206343],
  [1747180800000, 8860925.91388854],
  [1747267200000, 8854656.259617174],
  [1747353600000, 8861418.050018335],
  [1747440000000, 8862661.820151662],
  [1747526400000, 8833249.416670207],
  [1747612800000, 9065676.354329923],
  [1747699200000, 9017978.28123392],
  [1747785600000, 9134061.037906067],
  [1747872000000, 9387459.456660772],
  [1747958400000, 9591418.421810476],
  [1748044800000, 9121570.655984685],
  [1748131200000, 9173866.493436038],
  [1748217600000, 9274975.732278159],
  [1748304000000, 9314436.685236426],
  [1748390400000, 9310175.102671716],
  [1748476800000, 9208280.990679564],
  [1748563200000, 9026592.666677358],
  [1748649600000, 8900073.972215421],
  [1748736000000, 8957968.682594351],
  [1748822400000, 9040802.274014382],
  [1748908800000, 9038740.617012177],
  [1748995200000, 9036688.899610182],
  [1749081600000, 9003749.459208991],
  [1749168000000, 8729536.730077919],
  [1749254400000, 8957197.574287502],
  [1749340800000, 9066295.741750069],
  [1749427200000, 9066867.46885247],
  [1749513600000, 9455619.179043707],
  [1749600000000, 9440056.689266069],
  [1749686400000, 9288882.88186932],
  [1749772800000, 9081227.025134273],
  [1749859200000, 9132702.543985052],
  [1749945600000, 9084246.101299008],
  [1750032000000, 9090411.27477335],
  [1750118400000, 9208980.453923177],
  [1750204800000, 9039952.955659283],
  [1750291200000, 9070436.848135183],
  [1750377600000, 9080584.318377115],
  [1750464000000, 8945088.576284403],
  [1750550400000, 8792883.07729243],
  [1750636800000, 8731873.284684414],
  [1750723200000, 9111429.945371069],
  [1750809600000, 9111165.38661966],
  [1750896000000, 9223086.808659252],
  [1750982400000, 9165684.099752242],
  [1751068800000, 9156217.740562832],
  [1751155200000, 9177823.305095606],
  [1751241600000, 9263092.465181679],
  [1751328000000, 9181709.414667957],
  [1751414400000, 9054321.250569785],
  [1751500800000, 9325640.339018358],
  [1751587200000, 9360532.463404836],
  [1751673600000, 9250500.062624797],
  [1751760000000, 9285248.177863376],
  [1751846400000, 9337523.923073687],
  [1751932800000, 9302203.177316865],
  [1752019200000, 9338122.035800587],
  [1752105600000, 9541743.483380785],
  [1752192000000, 9934947.612549465],
  [1752278400000, 10091339.413757524],
  [1752364800000, 10078287.164944079],
  [1752451200000, 10222853.345055208],
  [1752537600000, 10301939.218478084],
  [1752624000000, 10119542.204331392],
  [1752710400000, 10198739.393321177],
  [1752796800000, 10277885.47839658],
  [1752883200000, 10164069.670952292],
  [1752969600000, 10156547.547410768],
  [1753056000000, 10101549.352407157],
  [1753142400000, 10136533.758092493],
  [1753228800000, 10357349.26643955],
  [1753315200000, 10249425.74900696],
  [1753401600000, 10229427.683390176],
  [1753488000000, 10168020.4311719],
  [1753574400000, 10203795.311577797],
  [1753660800000, 10330494.375551593],
  [1753747200000, 10240072.841855934],
  [1753833600000, 10260715.669243045],
  [1753920000000, 10330510.927890545],
  [1754006400000, 10122552.718401065],
  [1754092800000, 9870309.502282668],
  [1754179200000, 9811174.470132805],
  [1754265600000, 9963363.104407016],
  [1754352000000, 10119947.866363142],
  [1754438400000, 10011721.5506572],
  [1754524800000, 10094655.435390146],
  [1754611200000, 10270107.263258504],
  [1754697600000, 10236807.855788205],
  [1754784000000, 10220759.730383817],
  [1754870400000, 10434491.300112702],
  [1754956800000, 10412275.449238887],
  [1755043200000, 10529495.638104321],
  [1755129600000, 10805439.78369676],
  [1755216000000, 10383230.847886154],
  [1755302400000, 10268856.947554458],
  [1755388800000, 10282983.838569582],
  [1755475200000, 10286533.101169772],
  [1755561600000, 10148644.242275473],
  [1755648000000, 9819786.419050021],
  [1755734400000, 9942066.543754837],
  [1755820800000, 9813063.27750558],
  [1755907200000, 10203164.21582744],
  [1755993600000, 10074416.19618185],
  [1756080000000, 9903221.35080575],
  [1756166400000, 9653212.189243559],
  [1756252800000, 9801777.668906499],
  [1756339200000, 9749130.25886824],
  [1756425600000, 9856302.06893481],
  [1756512000000, 9564432.013993934],
  [1756598400000, 9591794.692119835],
  [1756684800000, 9545191.818462053],
  [1756771200000, 9606486.0790093],
  [1756857600000, 9784574.242949013],
  [1756944000000, 9838796.609221794],
  [1757030400000, 9765163.284050079],
  [1757116800000, 9759026.631183332],
  [1757203200000, 9718962.630296323],
  [1757289600000, 9800346.003033817],
  [1757376000000, 9856054.84901548],
  [1757462400000, 9840553.151484529],
  [1757548800000, 10035954.764445597],
  [1757635200000, 10195205.098488238],
  [1757721600000, 10254357.380846838],
  [1757808000000, 10237593.3071353],
  [1757894400000, 10184894.127284445],
  [1757980800000, 10169238.650025213],
  [1758067200000, 10261685.530263504],
  [1758153600000, 10237752.888404036],
  [1758240000000, 10333070.25718556],
  [1758326400000, 10189201.725638028],
  [1758412800000, 10194461.688819751],
  [1758499200000, 10158260.693491202],
  [1758585600000, 9951646.271657305],
  [1758672000000, 9948492.512889242],
  [1758758400000, 10060469.351465985],
  [1758844800000, 9673068.167457229],
  [1758931200000, 9728251.057537576],
  [1759017600000, 9723915.967631772],
  [1759104000000, 9944472.608696878],
  [1759190400000, 10139763.924082505],
  [1759276800000, 10130020.723922314],
  [1759363200000, 10509252.859358784],
  [1759449600000, 10700725.995237181],
  [1759536000000, 10847910.013598107],
  [1759622400000, 10859533.642673422],
  [1759708800000, 10959365.064936124],
  [1759795200000, 11070472.246732509],
  [1759881600000, 10783920.730192943],
  [1759968000000, 10949945.97908964],
  [1760054400000, 10814774.599012492],
  [1760140800000, 10047260.111235712],
  [1760227200000, 9838358.210748602],
  [1760313600000, 10223942.881584922],
  [1760400000000, 10216224.051870666],
  [1760486400000, 10046351.075825775],
  [1760572800000, 9721344.884648668],
  [1760659200000, 9509774.024195194],
  [1760745600000, 9369768.130232994],
  [1760832000000, 9432476.848616607],
  [1760918400000, 9558930.877185136],
  [1761004800000, 9720308.914971137],
  [1761091200000, 9549158.301143315],
  [1761177600000, 9442499.946295625],
  [1761264000000, 9659976.397607893],
  [1761350400000, 9747832.72977752],
  [1761436800000, 9802501.15016422],
  [1761523200000, 10055171.794296525],
  [1761609600000, 10073474.454011032],
  [1761696000000, 9965129.220872145],
  [1761782400000, 9722166.86543983],
  [1761868800000, 9593893.17104472],
  [1761955200000, 9734748.91964181],
  [1762041600000, 9765788.362963019],
  [1762128000000, 9824421.072227614],
  [1762214400000, 9450928.858755054],
  [1762300800000, 9018317.599498693],
  [1762387200000, 9199126.082980732],
  [1762473600000, 8984607.813501872],
  [1762560000000, 9167651.236387476],
  [1762646400000, 9069592.039128657],
  [1762732800000, 9283589.00601575],
  [1762819200000, 9394913.182233905],
  [1762905600000, 9108594.696793688],
  [1762992000000, 8994239.327086337],
  [1763078400000, 8857694.85444411],
  [1763164800000, 8376936.116014769],
  [1763251200000, 8470582.749251666],
  [1763337600000, 8373085.239387692],
  [1763424000000, 8157780.455111292],
  [1763510400000, 8219844.429070548],
  [1763596800000, 8084502.70583037],
  [1763683200000, 7685198.360480496],
  [1763769600000, 7622398.708162882],
  [1763856000000, 7591078.566298594],
  [1763942400000, 7778520.446850556],
  [1764028800000, 7865475.253834086],
  [1764115200000, 7783791.323601658],
  [1764201600000, 8066930.863801428],
  [1764288000000, 8157156.351483771],
  [1764374400000, 8126220.637986011],
  [1764460800000, 8116488.479072998],
  [1764547200000, 8078246.317717989],
  [1764633600000, 7731939.31508293],
  [1764720000000, 8213485.439946512],
  [1764806400000, 8441734.894689914],
  [1764892800000, 8277612.193785475],
  [1764979200000, 8033337.656068311],
  [1765065600000, 8028324.929700683],
  [1765152000000, 8110183.521497487],
  [1765238400000, 8167418.75650716],
  [1765324800000, 8337407.11660591],
  [1765411200000, 8261440.281355997],
  [1765497600000, 8347818.307928058],
  [1765584000000, 8175319.49414227],
  [1765670400000, 8175924.735194205],
  [1765756800000, 7992348.231966222],
  [1765843200000, 7844409.288926788],
  [1765929600000, 7987315.985984798],
  [1766016000000, 7781471.915537124],
  [1766102400000, 7712879.171308659],
  [1766188800000, 7892110.371399885],
  [1766275200000, 7913974.621357582],
  [1766361600000, 7933999.65474005],
  [1766448000000, 7929162.75966298],
  [1766534400000, 7820620.968822208],
  [1766620800000, 7872946.774052088],
  [1766707200000, 7860175.221034703],
  [1766793600000, 7838865.798860937],
  [1766880000000, 7886342.002067149],
  [1766966400000, 7887770.596681177],
  [1767052800000, 7835388.056690424],
  [1767139200000, 7936951.056508718],
  [1767225600000, 7875103.91153735],
  [1767312000000, 7982611.090931888],
  [1767398400000, 8094664.567193232],
  [1767484800000, 8154755.980058913],
  [1767571200000, 8224912.970329631],
  [1767657600000, 8475311.204337161],
  [1767744000000, 8443838.294347357],
  [1767830400000, 8200790.873528976],
  [1767916800000, 8179932.125614385],
  [1768003200000, 8169727.593041189],
  [1768089600000, 8164051.8328820085],
  [1768176000000, 8196362.9552232],
  [1768262400000, 8214254.506811856],
  [1768348800000, 8600260.479528198],
  [1768435200000, 8754772.557780331],
  [1768521600000, 8637202.771129187],
  [1768608000000, 8665871.041073622],
  [1768694400000, 8641731.269593248],
  [1768780800000, 8504968.615885023],
  [1768867200000, 8414003.970645163],
  [1768953600000, 8046939.8302773405],
  [1769040000000, 8179241.969294843],
  [1769126400000, 8189307.776814618],
  [1769212800000, 8190756.883147298],
  [1769299200000, 8167427.829795334],
  [1769385600000, 7931480.8104405],
  [1769472000000, 8098992.121060789],
  [1769558400000, 8165356.488930265],
  [1769644800000, 8206661.924142179],
  [1769731200000, 7762053.970031044],
  [1769817600000, 7714332.820802952],
  [1769904000000, 7217787.461780625],
  [1769990400000, 7055170.4747747015],
  [1770076800000, 7124353.514366637],
  [1770163200000, 6839512.652076184],
  [1770249600000, 6617843.606631121],
  [1770336000000, 5676634.189757013],
  [1770422400000, 6389223.0613750955],
  [1770508800000, 6278047.808376017],
  [1770595200000, 6388983.809905373],
  [1770681600000, 6363124.007122537],
  [1770768000000, 6230645.199778009],
  [1770854400000, 6073656.888033923],
  [1770940800000, 5993963.2553228345],
  [1771027200000, 6234117.350281114],
  [1771113600000, 6317657.207954805],
  [1771200000000, 6222983.54818252],
  [1771286400000, 6255749.578602175],
  [1771372800000, 6116329.755578176],
  [1771459200000, 6033801.7653913135],
  [1771545600000, 6092367.347486159],
  [1771632000000, 6166730.671036533],
  [1771718400000, 6167421.5569663085],
  [1771804800000, 6132044.38390857],
  [1771891200000, 5877904.816486458],
  [1771977600000, 5825506.041087636],
  [1772018280000, 5931411.726088468]],
 'market_caps': [[1740528000000, 153247587387219.9],
  [1740614400000, 145092897422240.22],
  [1740700800000, 146670947325212.53],
  [1740787200000, 146493284420451.72],
  [1740873600000, 149188251730084.6],
  [1740960000000, 163410530927229.25],
  [1741046400000, 149181798210246.72],
  [1741132800000, 151011753968614.66],
  [1741219200000, 156140079921156.88],
  [1741305600000, 155332618990098.5],
  [1741392000000, 149934788269021.75],
  [1741478400000, 148837480868612.94],
  [1741564800000, 139583949185400.2],
  [1741651200000, 136582014886006.11],
  [1741737600000, 143269950032252.84],
  [1741824000000, 144904649435288.6],
  [1741910400000, 139813920027311.94],
  [1741996800000, 144832172272915.2],
  [1742083200000, 145556393063008.88],
  [1742169600000, 142477016504235.94],
  [1742256000000, 144960350656778.97],
  [1742342400000, 142195295862922.2],
  [1742428800000, 148635356385415.66],
  [1742515200000, 144391367721865.88],
  [1742601600000, 143324180216465.75],
  [1742688000000, 142972251116074.03],
  [1742774400000, 146369361522808.2],
  [1742860800000, 148236568994576.1],
  [1742947200000, 148531315670993.2],
  [1743033600000, 147738113790149.78],
  [1743120000000, 148250573414973.28],
  [1743206400000, 143127644099250.1],
  [1743292800000, 140340804500989.94],
  [1743379200000, 139770328164058.75],
  [1743465600000, 139683227029930.31],
  [1743552000000, 144692611411592.8],
  [1743638400000, 140315492944612.62],
  [1743724800000, 140931082892341.03],
  [1743811200000, 142452612689242.22],
  [1743897600000, 141638568405765.44],
  [1743984000000, 133026191892504.16],
  [1744070400000, 136030860146543.77],
  [1744156800000, 130952471210149.42],
  [1744243200000, 141431144678745.16],
  [1744329600000, 136293671033013.61],
  [1744416000000, 142543573292291.38],
  [1744502400000, 145604183184316.78],
  [1744588800000, 142622853806903.7],
  [1744675200000, 144345816768012.4],
  [1744761600000, 142370094856537.44],
  [1744848000000, 143029004221568.34],
  [1744934400000, 143976048009443.06],
  [1745020800000, 143134711526525.56],
  [1745107200000, 144305951874866.28],
  [1745193600000, 144213572928166.12],
  [1745280000000, 147811055811997.84],
  [1745366400000, 158412191601745.1],
  [1745452800000, 158915548781568.0],
  [1745539200000, 158882010025594.88],
  [1745625600000, 160704481873690.8],
  [1745712000000, 160449211873569.97],
  [1745798400000, 159053087736354.47],
  [1745884800000, 160703590988217.25],
  [1745971200000, 159335269302606.8],
  [1746057600000, 158243639764679.06],
  [1746144000000, 162184675927639.97],
  [1746230400000, 162765758571135.0],
  [1746316800000, 161212206683015.7],
  [1746403200000, 158302280917006.22],
  [1746489600000, 158547084714911.78],
  [1746576000000, 163011406532277.9],
  [1746662400000, 163454639004415.8],
  [1746748800000, 176189564081226.4],
  [1746835200000, 174667261488634.56],
  [1746921600000, 177407732339299.34],
  [1747008000000, 176433904354746.88],
  [1747094400000, 173674333299646.56],
  [1747180800000, 175999429237788.7],
  [1747267200000, 175888780326749.9],
  [1747353600000, 176029183872811.16],
  [1747440000000, 176106843788904.56],
  [1747526400000, 175472918502628.47],
  [1747612800000, 179969199355517.6],
  [1747699200000, 179155548290416.03],
  [1747785600000, 181486652295308.97],
  [1747872000000, 186509837960828.16],
  [1747958400000, 190410208940880.75],
  [1748044800000, 181347759081015.84],
  [1748131200000, 182278846776151.78],
  [1748217600000, 184292802432865.47],
  [1748304000000, 185054409080508.47],
  [1748390400000, 185024049829002.9],
  [1748476800000, 183019605072651.28],
  [1748563200000, 179374386620553.34],
  [1748649600000, 176855933911134.62],
  [1748736000000, 178022821809896.6],
  [1748822400000, 179702340560357.03],
  [1748908800000, 179629331590192.03],
  [1748995200000, 179585658320534.6],
  [1749081600000, 178948840966760.94],
  [1749168000000, 173498311645619.7],
  [1749254400000, 178027023469230.2],
  [1749340800000, 180204160164195.62],
  [1749427200000, 180205822652402.1],
  [1749513600000, 187967193249811.56],
  [1749600000000, 187524509763221.47],
  [1749686400000, 184575081521565.3],
  [1749772800000, 180624143535765.12],
  [1749859200000, 181539805900760.34],
  [1749945600000, 180636698742719.03],
  [1750032000000, 180723901772300.84],
  [1750118400000, 183221269148744.34],
  [1750204800000, 179702316313150.78],
  [1750291200000, 180302143667231.16],
  [1750377600000, 180531137316963.9],
  [1750464000000, 177890103970304.6],
  [1750550400000, 174711454616211.44],
  [1750636800000, 173609591377867.56],
  [1750723200000, 181149919791061.84],
  [1750809600000, 181156284017729.62],
  [1750896000000, 183375534968167.0],
  [1750982400000, 182252346979144.12],
  [1751068800000, 182050553824902.0],
  [1751155200000, 182496862611105.2],
  [1751241600000, 184172362843128.75],
  [1751328000000, 182589937080075.4],
  [1751414400000, 180042186852721.9],
  [1751500800000, 185433877443111.84],
  [1751587200000, 186153377423026.12],
  [1751673600000, 183964052155743.7],
  [1751760000000, 184674889643392.38],
  [1751846400000, 185655570923395.9],
  [1751932800000, 184993020620040.47],
  [1752019200000, 185732711341357.97],
  [1752105600000, 189862956245589.16],
  [1752192000000, 197472885391991.06],
  [1752278400000, 200727427668076.25],
  [1752364800000, 200459098474667.5],
  [1752451200000, 203315574509896.47],
  [1752537600000, 204934287036692.16],
  [1752624000000, 201329642820657.56],
  [1752710400000, 202964035111987.44],
  [1752796800000, 204467504015373.97],
  [1752883200000, 202194802954273.38],
  [1752969600000, 202042587795977.12],
  [1753056000000, 201050515863258.1],
  [1753142400000, 201670805141508.38],
  [1753228800000, 206145479119255.44],
  [1753315200000, 203895633737564.28],
  [1753401600000, 203523367873936.34],
  [1753488000000, 202325740297391.03],
  [1753574400000, 203017861799776.94],
  [1753660800000, 205584489488322.06],
  [1753747200000, 203882439269756.53],
  [1753833600000, 204174804126429.94],
  [1753920000000, 205475160109208.53],

In [13]:
import pandas as pd
coin_id='tether'
url=f'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365'
response=requests.get(url)

response.json()#pandas datetime convert milliseconds into date

{'status': {'error_code': 429,
  'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}

In [14]:
import pandas as pd
coin_df=pd.DataFrame(records)
coin_df

                           ID  Market_cap_Rank
0                     bitcoin                1
1                    ethereum                2
2                      tether                3
3                      ripple                4
4                 binancecoin                5
..                        ...              ...
245                   arweave              239
246                eigenlayer              246
247  quantum-resistant-ledger              247
248         re-protocol-reusd              248
249                  frax-usd              249

[250 rows x 2 columns]

In [15]:
!pip install pycoingecko

Collecting pycoingecko
  Downloading pycoingecko-3.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pycoingecko) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pycoingecko) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pycoingecko) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pycoingecko) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pycoingecko) (2026.1.4)
Downloading pycoingecko-3.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pycoingecko
Successfully installed pycoingecko-3.2.0

In [16]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
from datetime import datetime

# Initialize the API client
cg = CoinGeckoAPI()

# 1. Fetch historical market data (365 days)
# 'days=365' automatically gives daily data (00:00 UTC)
coin_id = 'bitcoin'
data = cg.get_coin_market_chart_by_id(id=coin_id, vs_currency='usd', days=365)

# 2. Extract the 'prices' list
# Data format is: [[timestamp, price], [timestamp, price], ...]
prices = data['prices']

# 3. Create the DataFrame
df = pd.DataFrame(prices, columns=['date', 'price_usd'])

# 4. Clean the data
# Convert UNIX timestamp (ms) to readable Date
df['date'] = pd.to_datetime(df['date'], unit='ms').dt.date

# Add the coin_id column
df['coin_id'] = coin_id

# 5. Reorder columns to match your request
coins_df = df[['coin_id', 'date', 'price_usd']]

print(coins_df.head())

   coin_id        date     price_usd
0  bitcoin  2025-02-26  88755.769336
1  bitcoin  2025-02-27  83900.114965
2  bitcoin  2025-02-28  84709.144778
3  bitcoin  2025-03-01  84441.901224
4  bitcoin  2025-03-02  86005.256297

In [17]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
from datetime import datetime

# Initialize the API client
cg = CoinGeckoAPI()

# 1. Fetch historical market data (365 days)|
# 'days=365' automatically gives daily data (00:00 UTC)
coin_id = 'ethereum'
data = cg.get_coin_market_chart_by_id(id=coin_id, vs_currency='usd', days=365)

# 2. Extract the 'prices' list
# Data format is: [[timestamp, price], [timestamp, price], ...]
prices = data['prices']

# 3. Create the DataFrame
df = pd.DataFrame(prices, columns=['date', 'price_usd'])

# 4. Clean the data
# Convert UNIX timestamp (ms) to readable Date
df['date'] = pd.to_datetime(df['date'], unit='ms').dt.date

# Add the coin_id column
df['coin_id'] = coin_id

# 5. Reorder columns to match your request
coins_df = df[['coin_id', 'date', 'price_usd']]

print(coins_df.head())

    coin_id        date    price_usd
0  ethereum  2025-02-26  2495.315452
1  ethereum  2025-02-27  2325.853935
2  ethereum  2025-02-28  2305.322938
3  ethereum  2025-03-01  2235.204209
4  ethereum  2025-03-02  2212.824351

In [18]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
from datetime import datetime

# Initialize the API client
cg = CoinGeckoAPI()

# 1. Fetch historical market data (365 days)
# 'days=365' automatically gives daily data (00:00 UTC)
coin_id = 'tether'
data = cg.get_coin_market_chart_by_id(id=coin_id, vs_currency='usd', days=365)

# 2. Extract the 'prices' list
# Data format is: [[timestamp, price], [timestamp, price], ...]
prices = data['prices']

# 3. Create the DataFrame
df = pd.DataFrame(prices, columns=['date', 'price_usd'])

# 4. Clean the data
# Convert UNIX timestamp (ms) to readable Date
df['date'] = pd.to_datetime(df['date'], unit='ms').dt.date

# Add the coin_id column
df['coin_id'] = coin_id

# 5. Reorder columns to match your request
coins_df = df[['coin_id', 'date', 'price_usd']]

print(coins_df.head())

  coin_id        date  price_usd
0  tether  2025-02-26   0.998930
1  tether  2025-02-27   0.998532
2  tether  2025-02-28   0.999051
3  tether  2025-03-01   0.999445
4  tether  2025-03-02   0.999601

#oil_Price

In [19]:
import pandas as pd
oil_df=pd.read_csv('https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv')
oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10095  2026-02-10  64.20
10096  2026-02-11  64.80
10097  2026-02-12  63.08
10098  2026-02-13  63.05
10099  2026-02-17  62.53

[10100 rows x 2 columns]

In [20]:
import pandas as pd
from datetime import datetime, timedelta

# Load your data
df = pd.read_csv('https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv')

# Step 1: Ensure the 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Step 2: Define the timeframe (past 6 years from today)
six_years_ago = datetime.now() - pd.DateOffset(years=6)

# Step 3: Filter the data
filtered_df = df[df['Date'] >= six_years_ago]

print(filtered_df)

            Date  Price
8606  2020-02-26  48.67
8607  2020-02-27  47.17
8608  2020-02-28  44.83
8609  2020-03-02  46.78
8610  2020-03-03  47.27
...          ...    ...
10095 2026-02-10  64.20
10096 2026-02-11  64.80
10097 2026-02-12  63.08
10098 2026-02-13  63.05
10099 2026-02-17  62.53

[1494 rows x 2 columns]

# Stock_price

In [21]:
import yfinance as yf

In [22]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipython-input-1369541528.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker            ^IXIC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

In [23]:
df_nsei = stocks_df['^NSEI'].reset_index() # collect 3 ticker data similarly and then concat them.
# handle the  nulls
df_nsei.head()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [24]:
df_ixic = stocks_df['^IXIC'].reset_index() # collect 3 ticker data similarly and then concat them.
# handle the  nulls
df_ixic.head()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09

In [25]:
df_gspc = stocks_df['^GSPC'].reset_index() # collect 3 ticker data similarly and then concat them.
# handle the  nulls
df_gspc.head()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09

In [26]:
# Assuming each DF has a 'Close' column and 'Date' as the index
combined_df = pd.concat([df_nsei['Close'], df_gspc['Close'], df_ixic['Close']], axis=1)

# Rename columns for clarity
combined_df.columns = ['Nifty_50', 'S&P_500', 'Nasdaq']

In [27]:
# Assuming each DF has a 'Close' column and 'Date' as the index
combined_df = pd.concat([df_nsei['Close'], df_gspc['Close'], df_ixic['Close']], axis=1)

# Rename columns for clarity
combined_df.columns = ['Nifty_50', 'S&P_500', 'Nasdaq']

In [28]:
# Assuming each DF has a 'Close' column and 'Date' as the index
combined_df = pd.concat([df_nsei['Close'], df_gspc['Close'], df_ixic['Close']], axis=1)

# Rename columns for clarity
combined_df.columns = ['Nifty_50', 'S&P_500', 'Nasdaq']

In [29]:
# Assuming each DF has a 'Close' column and 'Date' as the index
combined_df = pd.concat([df_nsei['Close'], df_gspc['Close'], df_ixic['Close']], axis=1)

# Rename columns for clarity
combined_df.columns = ['Nifty_50', 'S&P_500', 'Nasdaq']
combined_df.head()

       Nifty_50      S&P_500       Nasdaq
0  12182.500000          NaN          NaN
1  12282.200195  3257.850098  9092.190430
2  12226.650391  3234.850098  9020.769531
3  11993.049805  3246.280029  9071.469727
4  12052.950195  3237.179932  9068.580078

#SQL Connection

In [30]:
import sqlite3

In [31]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine

# Create an SQLAlchemy engine
engine = create_engine('sqlite:///market_analytics.db')

# Assuming coins_df is already defined from previous steps
# If not, you might need to re-run the cells that create coins_df
# For example:
# coins_df = pd.DataFrame(Records)
# coins_df['Last_update'] = pd.to_datetime(coins_df['Last_update'])
# coins_df['date'] = coins_df['Last_update'].dt.date
# coins_df = coins_df.drop('Last_update', axis=1)
# coins_df = coins_df.rename(columns={'Id': 'id'})

coins_df.to_sql('coins_metadata', engine, if_exists='replace', index=False)

366

In [82]:
# Historical cryptocurrencies prices insertion from df_bitcoin_prices
import sqlite3
import pandas as pd
from sqlalchemy import create_engine, text
from pycoingecko import CoinGeckoAPI # Import CoinGeckoAPI

# Create an SQLAlchemy engine
engine = create_engine('sqlite:///market_analytics.db')

# Initialize the API client
cg = CoinGeckoAPI()

# Define the coin_id
coin_id = 'bitcoin'

# Fetch historical market data (365 days) using pycoingecko
# 'days=365' automatically gives daily data (00:00 UTC)
data = cg.get_coin_market_chart_by_id(id=coin_id, vs_currency='usd', days=365)

# Extract the 'prices' list
# Data format is: [[timestamp, price], [timestamp, price], ...]
prices = data['prices']

# Create a DataFrame
df_bitcoin_prices = pd.DataFrame(prices, columns=['timestamp', 'price_usd'])

# Convert timestamp to datetime and then to 'YYYY-MM-DD' date string
df_bitcoin_prices['date'] = pd.to_datetime(df_bitcoin_prices['timestamp'], unit='ms').dt.strftime('%Y-%m-%d')

# Add coin_id column
df_bitcoin_prices['coin_id'] = coin_id

# Select and reorder columns to match the desired schema for Crypto_prices table
df_bitcoin_prices = df_bitcoin_prices[['coin_id', 'date', 'price_usd']]

# Explicitly drop the table if it exists to avoid reflection issues with 'replace'
try:
    with engine.connect() as connection:
        connection.execute(text("DROP TABLE IF EXISTS Crypto_prices"))
        connection.commit()
    print("Table 'Crypto_prices' dropped if it existed.")
except Exception as e:
    print(f"Error dropping table: {e}")

# Insert historical cryptocurrencies prices into 'Crypto_prices' table.
df_bitcoin_prices.to_sql('Crypto_prices', engine, if_exists='replace', index=False)

print("Historical cryptocurrencies prices inserted into 'Crypto_prices' table.")

Table 'Crypto_prices' dropped if it existed.
Historical cryptocurrencies prices inserted into 'Crypto_prices' table.

In [33]:
#Connect to SQLite3 and create Database 'Market_Analysis'

In [34]:
#Create SQLalchemy engine to interact with SQLite3 database
# Save DataFrames to SQLite3 Database 'Market_Analysis'using SQLite3

In [35]:
#Connect to SQLite3 and create Database 'Market_Analysis'|

In [36]:
#Create SQLalchemy engine to interact with SQLite3 database
# Save DataFrames to SQLite3 Database 'Market_Analysis'using SQLite3

# Cryptocurrencies

In [37]:
import sqlite3
import pandas as pd
import requests

# 1. Connect to SQLite (create 'Market_Analytics.db' if it doesn't exist)
conn = sqlite3.connect('Market_Analytics.db')  # Added this line to create the connection
cursor = conn.cursor()

print('Connected to Market_Analytics.db')

Connected to Market_Analytics.db

In [38]:
import pandas as pd
import sqlite3
import json

# Prepare Crypto Data for DB
coins_df = pd.DataFrame(Records)

# Convert any list columns to JSON strings
for column in coins_df.columns:
    if coins_df[column].apply(lambda x: isinstance(x, list)).any():
        coins_df[column] = coins_df[column].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)

coins_df['Last_update'] = pd.to_datetime(coins_df['Last_update'])
coins_df['date'] = coins_df['Last_update'].dt.date
coins_df = coins_df.drop('Last_update', axis=1)
coins_df = coins_df.rename(columns={'Id': 'id'}) # Ensure 'id' column name matches DB schema for Cryptocurrencies

# Insert Cryptocurrencies Data
conn = sqlite3.connect('market_analytics.db')
coins_df.to_sql('Cryptocurrencies', conn, if_exists='replace', index=False)
conn.close()

print("Cryptocurrency data prepared and inserted into 'Cryptocurrencies' table.")

Cryptocurrency data prepared and inserted into 'Cryptocurrencies' table.

In [39]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('market_analytics.db')

# Query the Cryptocurrencies table for the top 10 by market_cap_rank
query = """
SELECT
    id,
    name,
    symbol,
    market_cap_rank,
    current_price,
    market_cap,
    total_volume
FROM
    Cryptocurrencies
ORDER BY
    market_cap_rank ASC
LIMIT 10;
"""

top_10_crypto_df = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Display the results
print("Top 5 Cryptocurrencies by Market Cap Rank:")
top_10_crypto_df

Top 5 Cryptocurrencies by Market Cap Rank:

,ID,Name,symbol,Market_cap_Rank,current_price,Market_cap,Total_volume
0,bitcoin,Bitcoin,btc,1,65241.000000,1305769714138,"[""total_volume""]"
1,bitcoin,Bitcoin,btc,1,65241.000000,1305769714138,"[""total_volume""]"
2,bitcoin,Bitcoin,btc,1,65241.000000,1305769714138,"[""total_volume""]"
3,ethereum,Ethereum,eth,2,1915.250000,231249290227,"[""total_volume""]"
4,ethereum,Ethereum,eth,2,1915.250000,231249290227,"[""total_volume""]"
5,ethereum,Ethereum,eth,2,1915.250000,231249290227,"[""total_volume""]"
6,tether,Tether,usdt,3,0.999818,183589915324,"[""total_volume""]"
7,tether,Tether,usdt,3,0.999818,183589915324,"[""total_volume""]"
8,tether,Tether,usdt,3,0.999818,183589915324,"[""total_volume""]"
9,ripple,XRP,xrp,4,1.380000,83921821776,"[""total_volume""]"

#Crypto_Prices

In [40]:
import sqlite3
import pandas as pd
import requests

# 1. Connect to SQLite (creates 'market_analytics.db' if it doesn't exist)
conn = sqlite3.connect('market_analytics.db')
cursor = conn.cursor()

print("Connected to market_analytics.db")

Connected to market_analytics.db

In [41]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine, text

# Connect to the correct SQLite database
conn = sqlite3.connect('market_analytics.db')

# Create an SQLAlchemy engine
engine = create_engine('sqlite:///market_analytics.db')

# Use the already prepared coins_df which contains the latest crypto data (tether)
# and has the columns 'ID', 'date', 'current_price'
crypto_price = coins_df.copy()

# Explicitly drop the table if it exists to avoid reflection issues with 'replace'
try:
    with engine.connect() as connection:
        connection.execute(text("DROP TABLE IF EXISTS crypto_prices"))
        connection.commit()
    print("Table 'crypto_prices' dropped if it existed.")
except Exception as e:
    print(f"Error dropping table: {e}")

# Insert the crypto price data into the 'crypto_prices' table.
crypto_price.to_sql('crypto_prices', engine, if_exists='replace', index=False)

print("crypto price data inserted into 'crypto_prices' table.")

# Now, try to query the table again with the correct column names
query = """
SELECT
    ID,
    date,
    current_price
FROM
    crypto_prices
ORDER BY
    date ASC
LIMIT 10;
"""
crypto_price_from_db = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Display the results
print("Top 10 rows from crypto_price table after insertion:")
crypto_price_from_db

Table 'crypto_prices' dropped if it existed.
crypto price data inserted into 'crypto_prices' table.
Top 10 rows from crypto_price table after insertion:

              ID        date  current_price
0  hashnote-usyc  2026-02-10       1.120000
1  hashnote-usyc  2026-02-10       1.120000
2  hashnote-usyc  2026-02-10       1.120000
3        bitcoin  2026-02-25   65241.000000
4       ethereum  2026-02-25    1915.250000
5         tether  2026-02-25       0.999818
6         ripple  2026-02-25       1.380000
7    binancecoin  2026-02-25     602.540000
8       usd-coin  2026-02-25       0.999803
9         solana  2026-02-25      82.540000

#oil_price

In [42]:
import sqlite3
import pandas as pd
import requests

# 1. Connect to SQLite (creates 'market_analytics.db' if it doesn't exist)
conn = sqlite3.connect('market_analytics.db')
cursor = conn.cursor()

print("Connected to market_analytics.db")

Connected to market_analytics.db

In [43]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine

# Connect to the correct SQLite database
conn = sqlite3.connect('market_analytics.db')

# Create an SQLAlchemy engine
engine = create_engine('sqlite:///market_analytics.db')

# Ensure 'Date' column is in datetime format for easier handling
oil_df['Date'] = pd.to_datetime(oil_df['Date'])

# Rename columns to match the schema defined in 7nu0jsk06Uo0
oil_df = oil_df.rename(columns={'Price': 'price_usd'})

# Insert the oil price data into the Oil_prices table
oil_df.to_sql('Oil_prices', engine, if_exists='replace', index=False)

print("Oil price data inserted into 'Oil_prices' table.")

# Now, try to query the table again
query = """
SELECT
    Date,
    price_usd
FROM
    Oil_prices
ORDER BY
    Date ASC
LIMIT 10;
"""
oil_df_from_db = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Display the results
print("Top 10 rows from Oil_prices table after insertion:")
oil_df_from_db

Oil price data inserted into 'Oil_prices' table.
Top 10 rows from Oil_prices table after insertion:

                         Date  price_usd
0  1986-01-02 00:00:00.000000      25.56
1  1986-01-03 00:00:00.000000      26.00
2  1986-01-06 00:00:00.000000      26.53
3  1986-01-07 00:00:00.000000      25.85
4  1986-01-08 00:00:00.000000      25.87
5  1986-01-09 00:00:00.000000      26.03
6  1986-01-10 00:00:00.000000      25.65
7  1986-01-13 00:00:00.000000      25.08
8  1986-01-14 00:00:00.000000      24.97
9  1986-01-15 00:00:00.000000      25.18

#stock_price

In [44]:
import sqlite3
import pandas as pd
import requests

# 1. Connect to SQLite (creates 'stock.db' if it doesn't exist)
conn = sqlite3.connect('stock.db')
cursor = conn.cursor()

print("Connected to stock.db")

Connected to stock.db

In [45]:
import yfinance as yf
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

# Define the tickers you want to download
tickers = ['^GSPC', '^IXIC', '^NSEI']
start_date = "2020-01-01"
end_date = "2026-01-12"

# Download data for all tickers without group_by. This often returns a (Metric, Ticker) MultiIndex
stocks_df_raw = yf.download(tickers, start=start_date, end=end_date)

# Flatten the MultiIndex columns to a single level, e.g., 'Open_^GSPC'
# This makes column access much simpler.
stocks_df_raw.columns = ['_'.join(col).strip() for col in stocks_df_raw.columns.values]

# Create a database connection
engine = create_engine('sqlite:///stocks.db')
conn = engine.connect()

all_stocks_data_for_db = []

# Iterate through each ticker to process its data
for ticker_symbol in tickers:
    # Select columns relevant to the current ticker
    # Look for 'Open_^GSPC', 'High_^GSPC', etc.
    cols_for_ticker = [col for col in stocks_df_raw.columns if col.endswith(f'_{ticker_symbol}')]
    df_single_ticker = stocks_df_raw[cols_for_ticker].copy()

    # Rename columns to standard names ('open', 'high', etc.)
    # Example: 'Open_^GSPC' -> 'open'
    new_column_names = {col: col.split('_')[0].lower() for col in df_single_ticker.columns}
    df_single_ticker = df_single_ticker.rename(columns=new_column_names)

    # Reset index to make 'Date' a column
    df_single_ticker = df_single_ticker.reset_index()
    df_single_ticker = df_single_ticker.rename(columns={'Date': 'date'})

    # Add the ticker column
    df_single_ticker['ticker'] = ticker_symbol

    # Handle 'Adj Close': if 'close' is not present but 'adj close' is, rename 'adj close' to 'close'.
    # Otherwise, if 'adj close' is present, drop it since 'close' is likely already adjusted.
    if 'adj close' in df_single_ticker.columns and 'close' not in df_single_ticker.columns:
        df_single_ticker = df_single_ticker.rename(columns={'adj close': 'close'})
    elif 'adj close' in df_single_ticker.columns:
        df_single_ticker = df_single_ticker.drop(columns=['adj close'])

    # Select only the columns needed for the database schema
    all_stocks_data_for_db.append(df_single_ticker[['date', 'ticker', 'open', 'high', 'low', 'close', 'volume']])

# Concatenate all individual ticker DataFrames into a single DataFrame
stocks_final_df = pd.concat(all_stocks_data_for_db, ignore_index=True)

# Ensure 'date' column is in a format compatible with SQLite DATE type (YYYY-MM-DD)
stocks_final_df['date'] = pd.to_datetime(stocks_final_df['date']).dt.strftime('%Y-%m-%d')

# Insert the stock price data into the Stock_prices table
# Using 'replace' for if_exists to ensure fresh data each run if table exists
stocks_final_df.to_sql('Stock_prices', engine, if_exists='replace', index=False)

print("Stock price data inserted into 'Stock_prices' table.")

# Now, try to query the table again
query = """
SELECT
    date,
    open,
    high,
    low,
    close,
    volume,
    ticker
FROM
    Stock_prices
ORDER BY
    date ASC
LIMIT 10;
"""
stocks_df_from_db = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Display the results
print("Top 10 rows from Stock_prices table after insertion:")
print(stocks_df_from_db)

/tmp/ipython-input-838244784.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df_raw = yf.download(tickers, start=start_date, end=end_date)
[*********************100%***********************]  3 of 3 completed

Stock price data inserted into 'Stock_prices' table.
Top 10 rows from Stock_prices table after insertion:
         date          open          high           low         close  \
0  2020-01-01           NaN           NaN           NaN           NaN
1  2020-01-01           NaN           NaN           NaN           NaN
2  2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000
3  2020-01-02   3244.669922   3258.139893   3235.530029   3257.850098
4  2020-01-02   9039.459961   9093.429688   9010.889648   9092.190430
5  2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195
6  2020-01-03   3226.360107   3246.149902   3222.340088   3234.850098
7  2020-01-03   8976.429688   9065.759766   8976.429688   9020.769531
8  2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391
9  2020-01-06   3217.550049   3246.840088   3214.639893   3246.280029

         volume ticker
0           NaN  ^GSPC
1           NaN  ^IXIC
2  3.041000e+05  ^NSEI
3  3.459930e+09  ^GSPC
4  2.862700e+09  ^IXIC
5  4.077000e+05  ^NSEI
6  3.484700e+09  ^GSPC
7  2.586520e+09  ^IXIC
8  4.288000e+05  ^NSEI
9  3.702460e+09  ^GSPC

# SQL QUERIES for cryptocurrencies
> Add blockquote

In [46]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query = """
SELECT
    Name,
    symbol,
    Market_cap
FROM
    Cryptocurrencies
ORDER BY
    Market_cap DESC
LIMIT 3;
"""

top_3_crypto = pd.read_sql_query(query, conn)
conn.close()

print("Top 3 Cryptocurrencies by Market Cap:")
print(top_3_crypto)

Top 3 Cryptocurrencies by Market Cap:
      Name symbol     Market_cap
0  Bitcoin    btc  1305769714138
1  Bitcoin    btc  1305769714138
2  Bitcoin    btc  1305769714138

In [47]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    symbol,
    name,
    circulating_supply,
    total_supply,
    (CAST(circulating_supply AS REAL) / total_supply) * 100 AS supply_percent
FROM
    Cryptocurrencies
WHERE
    total_supply > 0
    AND (CAST(circulating_supply AS REAL) / total_supply) >= 0.90
ORDER BY
    supply_percent DESC
LIMIT 3;
"""
top_3_crypto = pd.read_sql_query(query, conn)
conn.close()

print("Top 3 Cryptocurrencies by Circulating Supply Percentage:")
print(top_3_crypto)

Top 3 Cryptocurrencies by Circulating Supply Percentage:
  symbol Name  Circulating_Supply  Total_supply  supply_percent
0    dai  Dai        4.200128e+09  4.184992e+09      100.361669
1    dai  Dai        4.200128e+09  4.184992e+09      100.361669
2    dai  Dai        4.200128e+09  4.184992e+09      100.361669

In [48]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    C.Name,
    C.symbol,
    CP.current_price,
    C.ath,
    ((CP.current_price / C.ath) * 100) AS percent_of_ath
FROM
    crypto_prices AS CP
JOIN
    Cryptocurrencies AS C ON CP.ID = C.ID
WHERE
    C.ath > 0
    AND (CP.current_price / C.ath) >= 0.90
ORDER BY
    percent_of_ath DESC
LIMIT 3;
"""
top_3_crypto = pd.read_sql_query(query, conn)
conn.close()

print("Top 3 Cryptocurrencies by Percentage of All-Time High:")
print(top_3_crypto)

Top 3 Cryptocurrencies by Percentage of All-Time High:
                                                Name symbol  current_price  \
0  BlackRock USD Institutional Digital Liquidity ...  buidl            1.0
1  BlackRock USD Institutional Digital Liquidity ...  buidl            1.0
2  BlackRock USD Institutional Digital Liquidity ...  buidl            1.0

   ath  percent_of_ath
0  1.0           100.0
1  1.0           100.0
2  1.0           100.0

In [49]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    AVG(market_cap_rank) as average_rank,
    COUNT(*) as coin_count
FROM
    Cryptocurrencies
WHERE
    total_volume > 1000000000;
"""
top_3_crypto = pd.read_sql_query(query, conn)
conn.close()

print("Average Market Cap Rank and Count for Cryptocurrencies with Total Volume > $1 Billion:")
print(top_3_crypto)

Average Market Cap Rank and Count for Cryptocurrencies with Total Volume > $1 Billion:
   average_rank  coin_count
0       125.504         750

In [50]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    Name,
    symbol,
    date,
    current_price
FROM
    Cryptocurrencies
ORDER BY
    date DESC
LIMIT 1;
"""
top_3_crypto = pd.read_sql_query(query, conn)
conn.close()
print("Top 1 Cryptocurrencies by Last Updated:")
print(top_3_crypto)

Top 1 Cryptocurrencies by Last Updated:
      Name symbol        date  current_price
0  Bitcoin    btc  2026-02-25        65241.0

# SQL QUERIES for Crypto_Price

In [51]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')
c = conn.cursor()
query="""
SELECT
    MAX(current_price) AS highest_daily_price,
    date
FROM
    Crypto_prices
WHERE
    ID = 'bitcoin' AND date >= DATE('now', '-365 days')
GROUP BY
    date
ORDER BY
    highest_daily_price DESC
LIMIT 1;
"""
top_3_crypto = pd.read_sql_query(query, conn)
conn.close()
print("Highest Daily Price for Bitcoin in the Last Year:")
print(top_3_crypto)

Highest Daily Price for Bitcoin in the Last Year:
   highest_daily_price        date
0              65241.0  2026-02-25

In [52]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')
c = conn.cursor()
query="""
SELECT
    AVG(current_price) AS average_eth_price
FROM
    Crypto_prices
WHERE
    ID = 'ethereum' AND date >= DATE('now', '-365 days');
"""

average_eth_price_df = pd.read_sql_query(query, conn)
conn.close()
print("Average Ethereum price in the last year:")
print(average_eth_price_df)

Average Ethereum price in the last year:
   average_eth_price
0            1915.25

In [53]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query = """
SELECT
    date,
    current_price
FROM
    Crypto_prices
WHERE
    ID = 'bitcoin' AND date BETWEEN '2025-01-01' AND '2025-01-31'
ORDER BY
    date ASC;
"""

bitcoin_monthly_prices = pd.read_sql_query(query, conn)
conn.close()

print("Bitcoin prices for January 2025:")
print(bitcoin_monthly_prices)

Bitcoin prices for January 2025:
Empty DataFrame
Columns: [date, current_price]
Index: []

In [54]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    ID,
    AVG(current_price) AS annual_average_price
FROM
    Crypto_prices
WHERE
    date >= DATE('now', '-365 days')
GROUP BY
    ID
ORDER BY
    annual_average_price DESC
LIMIT 1;
"""
annual_average_crypto_price = pd.read_sql_query(query, conn)
conn.close()

print("Cryptocurrency with the highest annual average price in the last year:")
print(annual_average_crypto_price)

Cryptocurrency with the highest annual average price in the last year:
        ID  annual_average_price
0  bitcoin               65241.0

In [55]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query = """
WITH price_data AS (
    SELECT
        (SELECT current_price FROM Crypto_prices WHERE date = '2024-09-01' AND ID = 'bitcoin') AS start_price,
        (SELECT current_price FROM Crypto_prices WHERE date = '2025-09-01' AND ID = 'bitcoin') AS end_price
)
SELECT
    start_price,
    end_price,
    ((end_price - start_price) / start_price) * 100 AS percent_change
FROM price_data;
"""

price_change_df = pd.read_sql_query(query, conn)
conn.close()

print("Bitcoin Price Change (2024-09-01 to 2025-09-01):")
print(price_change_df)

Bitcoin Price Change (2024-09-01 to 2025-09-01):
  start_price end_price percent_change
0        None      None           None

#Oil_Price

> Add blockquote

In [56]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    MAX(price_usd) AS highest_oil_price,
    Date
FROM
    Oil_prices
WHERE
    Date >= DATE('now', '-5 years')
GROUP BY
    Date
ORDER BY
    highest_oil_price DESC
LIMIT 1;
"""

highest_oil_price_df = pd.read_sql_query(query, conn)
conn.close()

print("Highest oil price in the last 5 years:")
print(highest_oil_price_df)

Highest oil price in the last 5 years:
   highest_oil_price                        Date
0             123.64  2022-03-08 00:00:00.000000

In [57]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    STRFTIME('%Y', Date) AS Year,
    AVG(price_usd) AS Average_Price
FROM
    Oil_prices
GROUP BY
    Year
ORDER BY
    Year DESC;
"""

average_annual_oil_price_df = pd.read_sql_query(query, conn)
conn.close()

print("Average annual oil prices:")
print(average_annual_oil_price_df)

Average annual oil prices:
    Year  Average_Price
0   2026      61.238065
1   2025      65.388105
2   2024      76.632240
3   2023      77.576532
4   2022      94.902869
5   2021      68.135100
6   2020      39.160437
7   2019      56.988320
8   2018      65.227470
9   2017      50.800320
10  2016      43.293651
11  2015      48.656706
12  2014      93.172222
13  2013      97.982540
14  2012      94.053333
15  2011      94.880873
16  2010      79.475714
17  2009      61.950437
18  2008      99.671502
19  2007      72.340595
20  2006      66.054659
21  2005      56.637251
22  2004      41.506024
23  2003      31.075240
24  2002      26.184960
25  2001      25.983120
26  2000      30.378520
27  1999      19.344980
28  1998      14.422072
29  1997      20.608254
30  1996      22.119173
31  1995      18.428805
32  1994      17.196429
33  1993      18.432200
34  1992      20.575564
35  1991      21.541367
36  1990      24.526576
37  1989      19.635486
38  1988      15.965409
39  1987      19.200512
40  1986      15.047689

In [58]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    Date,
    price_usd
FROM
    Oil_prices
WHERE
    Date BETWEEN '2020-03-01' AND '2020-04-30'
ORDER BY
    price_usd ASC;
"""

oil_prices_df = pd.read_sql_query(query, conn)
conn.close()

print("Oil prices between 2020-03-01 and 2020-04-30:")
print(oil_prices_df)

Oil prices between 2020-03-01 and 2020-04-30:
                          Date  price_usd
0   2020-04-20 00:00:00.000000     -36.98
1   2020-04-21 00:00:00.000000       8.91
2   2020-04-27 00:00:00.000000      12.17
3   2020-04-28 00:00:00.000000      12.40
4   2020-04-22 00:00:00.000000      13.64
5   2020-03-30 00:00:00.000000      14.10
6   2020-04-29 00:00:00.000000      15.04
7   2020-04-23 00:00:00.000000      15.06
8   2020-03-27 00:00:00.000000      15.48
9   2020-04-24 00:00:00.000000      15.99
10  2020-03-26 00:00:00.000000      16.60
11  2020-04-17 00:00:00.000000      18.31
12  2020-03-20 00:00:00.000000      19.48
13  2020-04-16 00:00:00.000000      19.82
14  2020-04-15 00:00:00.000000      19.96
15  2020-04-14 00:00:00.000000      20.15
16  2020-04-01 00:00:00.000000      20.28
17  2020-03-18 00:00:00.000000      20.48
18  2020-03-31 00:00:00.000000      20.51
19  2020-03-25 00:00:00.000000      20.75
20  2020-03-24 00:00:00.000000      21.03
21  2020-04-13 00:00:00.000000      22.36
22  2020-04-09 00:00:00.000000      22.90
23  2020-03-23 00:00:00.000000      23.33
24  2020-04-07 00:00:00.000000      23.54
25  2020-04-08 00:00:00.000000      24.97
26  2020-03-19 00:00:00.000000      25.09
27  2020-04-02 00:00:00.000000      25.18
28  2020-04-06 00:00:00.000000      26.21
29  2020-03-17 00:00:00.000000      26.96
30  2020-04-03 00:00:00.000000      28.36
31  2020-03-16 00:00:00.000000      28.96
32  2020-03-09 00:00:00.000000      31.05
33  2020-03-12 00:00:00.000000      31.56
34  2020-03-13 00:00:00.000000      31.72
35  2020-03-11 00:00:00.000000      33.13
36  2020-03-10 00:00:00.000000      34.47
37  2020-03-06 00:00:00.000000      41.14
38  2020-03-05 00:00:00.000000      45.90
39  2020-03-02 00:00:00.000000      46.78
40  2020-03-04 00:00:00.000000      46.78
41  2020-03-03 00:00:00.000000      47.27

In [59]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    Date,
    MIN(price_usd) AS lowest_oil_price
FROM
    Oil_prices
WHERE
    Date >= DATE('now', '-10 years')
GROUP BY
    Date
ORDER BY
    lowest_oil_price ASC
LIMIT 1;
"""

lowest_oil_price_df = pd.read_sql_query(query, conn)
conn.close()

print("Lowest oil price in the last 10 years:")
print(lowest_oil_price_df)

Lowest oil price in the last 10 years:
                         Date  lowest_oil_price
0  2020-04-20 00:00:00.000000            -36.98

In [60]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query="""
SELECT
    STRFTIME('%Y', Date) AS Year,
    MAX(price_usd) AS Yearly_High,
    MIN(price_usd) AS Yearly_Low,
    (MAX(price_usd) - MIN(price_usd)) AS Volatility_Range
FROM
    Oil_prices
GROUP BY
    Year
ORDER BY
    Year DESC;
"""

oil_volatility_df = pd.read_sql_query(query, conn)
conn.close()

print("Annual Oil Price Volatility:")
print(oil_volatility_df)

Annual Oil Price Volatility:
    Year  Yearly_High  Yearly_Low  Volatility_Range
0   2026        64.80       56.01              8.79
1   2025        80.73       55.44             25.29
2   2024        87.69       66.73             20.96
3   2023        93.67       66.61             27.06
4   2022       123.64       71.05             52.59
5   2021        85.64       47.47             38.17
6   2020        63.27      -36.98            100.25
7   2019        66.24       46.31             19.93
8   2018        77.41       44.48             32.93
9   2017        60.46       42.48             17.98
10  2016        54.01       26.19             27.82
11  2015        61.36       34.55             26.81
12  2014       107.95       53.45             54.50
13  2013       110.62       86.65             23.97
14  2012       109.39       77.72             31.67
15  2011       113.39       75.40             37.99
16  2010        91.48       64.78             26.70
17  2009        81.03       34.03             47.00
18  2008       145.31       30.28            115.03
19  2007        99.16       50.51             48.65
20  2006        77.05       55.90             21.15
21  2005        69.91       42.16             27.75
22  2004        56.37       32.49             23.88
23  2003        37.96       25.25             12.71
24  2002        32.68       18.02             14.66
25  2001        32.21       17.50             14.71
26  2000        37.22       23.91             13.31
27  1999        28.03       11.38             16.65
28  1998        17.93       10.82              7.11
29  1997        26.55       17.60              8.95
30  1996        26.55       17.33              9.22
31  1995        20.53       16.86              3.67
32  1994        20.72       13.89              6.83
33  1993        21.05       13.98              7.07
34  1992        23.03       17.89              5.14
35  1991        32.25       17.43             14.82
36  1990        41.07       15.43             25.64
37  1989        24.62       16.99              7.63
38  1988        18.54       12.58              5.96
39  1987        22.44       15.12              7.32
40  1986        26.53       10.25             16.28

#Stock_price

In [61]:
import sqlite3
import pandas as pd

# Connect to the database where stock prices are stored
conn = sqlite3.connect('stocks.db')

query = """
SELECT
    date,
    open,
    high,
    low,
    close,
    volume
FROM
    Stock_prices
WHERE
    ticker = 'AAPL' -- Replace 'AAPL' with your desired ticker
ORDER BY
    date ASC;
"""

stock_data_df = pd.read_sql_query(query, conn)
conn.close()

print(f"Historical data for AAPL:\n{stock_data_df.head()}")

Historical data for AAPL:
Empty DataFrame
Columns: [date, open, high, low, close, volume]
Index: []

In [62]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('stocks.db')

query = """
SELECT
    MAX(close) AS highest_closing_price,
    date
FROM
    Stock_prices
WHERE
    ticker = '^IXIC'
GROUP BY
    date
ORDER BY
    highest_closing_price DESC
LIMIT 1;
"""

highest_close_price_ixic = pd.read_sql_query(query, conn)
conn.close()

print("Highest closing price for NASDAQ (^IXIC):")
print(highest_close_price_ixic)

Highest closing price for NASDAQ (^IXIC):
   highest_closing_price        date
0           23958.470703  2025-10-29

In [63]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('stocks.db')

query = """
SELECT
    date,
    high,
    low,
    (high - low) AS Daily_Difference,
    ((high - low) / low * 100) AS Percentage_Volatility
FROM
    Stock_prices
WHERE
    ticker = '^GSPC'
ORDER BY
    Daily_Difference DESC
LIMIT 5;
"""

sp500_volatility = pd.read_sql_query(query, conn)
conn.close()

print("Top 5 Days with Highest Daily Volatility for S&P 500:")
print(sp500_volatility)

Top 5 Days with Highest Daily Volatility for S&P 500:
         date         high          low  Daily_Difference  \
0  2025-04-09  5481.339844  4948.430176        532.909668
1  2025-04-07  5246.569824  4835.040039        411.529785
2  2025-04-08  5267.470215  4910.419922        357.050293
3  2025-04-10  5353.149902  5115.270020        237.879883
4  2025-11-20  6770.350098  6534.049805        236.300293

   Percentage_Volatility
0              10.769267
1               8.511404
2               7.271278
3               4.650388
4               3.616445

In [64]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('stocks.db')

query = """
SELECT
    ticker,
    STRFTIME('%Y-%m', date) AS month,
    AVG(close) AS avg_closing_price
FROM
    Stock_prices
GROUP BY
    ticker, month
ORDER BY
    month DESC, ticker ASC;
"""

avg_monthly_closing_price = pd.read_sql_query(query, conn)
conn.close()

print("Average Monthly Closing Price for Stocks:")
print(avg_monthly_closing_price)

Average Monthly Closing Price for Stocks:
    ticker    month  avg_closing_price
0    ^GSPC  2026-01        6919.001628
1    ^IXIC  2026-01       23485.711589
2    ^NSEI  2026-01       26086.428850
3    ^GSPC  2025-12        6853.025457
4    ^IXIC  2025-12       23377.326882
..     ...      ...                ...
214  ^IXIC  2020-02        9418.850021
215  ^NSEI  2020-02       11948.821186
216  ^GSPC  2020-01        3278.202858
217  ^IXIC  2020-01        9233.359980
218  ^NSEI  2020-01       12183.065132

[219 rows x 3 columns]

In [65]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('stocks.db')

query = """
SELECT
    AVG(volume) AS average_volume_2024
FROM
    Stock_prices
WHERE
    ticker = '^NSEI'
    AND date BETWEEN '2024-01-01' AND '2024-12-31';
"""

average_volume_2024_df = pd.read_sql_query(query, conn)
conn.close()

print("Average trading volume for Nifty 50 in 2024:")
print(average_volume_2024_df)

Average trading volume for Nifty 50 in 2024:
   average_volume_2024
0        313560.162602

# Join Query

In [83]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('market_analytics.db')

query = """
SELECT
    CP.date AS price_date,
    CP.price_usd AS btc_price,
    OP.price_usd AS oil_price
FROM
    Crypto_prices AS CP
JOIN
    Oil_prices AS OP ON CP.date = STRFTIME('%Y-%m-%d', OP.Date)
WHERE
    CP.coin_id = 'bitcoin'
    AND CP.date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY
    CP.date ASC;
"""

joined_prices_df = pd.read_sql_query(query, conn)
conn.close()

print("Bitcoin and Oil Prices for 2025:")
print(joined_prices_df.head())

Bitcoin and Oil Prices for 2025:
   price_date     btc_price  oil_price
0  2025-02-26  88755.769336      68.87
1  2025-02-27  83900.114965      70.62
2  2025-02-28  84709.144778      69.97
3  2025-03-03  94261.532865      68.63
4  2025-03-04  86124.714187      68.47

In [75]:
import sqlite3
import pandas as pd

# --- Step 1: Fetch Bitcoin price data from market_analytics.db ---
conn_crypto = sqlite3.connect('market_analytics.db')
query_btc = """
SELECT
    date,
    current_price
FROM
    Crypto_prices
WHERE
    ID = 'bitcoin' AND date >= '2024-01-01'
ORDER BY
    date ASC;
"""
df_btc = pd.read_sql_query(query_btc, conn_crypto)
conn_crypto.close()

# --- Step 2: Fetch S&P 500 closing price data from stocks.db ---
conn_stocks = sqlite3.connect('stocks.db')
query_spx = """
SELECT
    date,
    close
FROM
    Stock_prices
WHERE
    ticker = '^GSPC' AND date >= '2024-01-01'
ORDER BY
    date ASC;
"""
df_spx = pd.read_sql_query(query_spx, conn_stocks)
conn_stocks.close()

# --- Step 3: Merge the two DataFrames on their common date column ---
# Ensure date columns are datetime objects for proper merging
df_btc['date'] = pd.to_datetime(df_btc['date'])
df_spx['date'] = pd.to_datetime(df_spx['date'])

# Merge dataframes
merged_df = pd.merge(df_btc, df_spx, on='date', how='inner')

# --- Step 4: Calculate the correlation ---
# Rename columns for clarity in correlation calculation if needed, or directly use them
# For simplicity, let's just use the existing column names after merge
correlation = merged_df['current_price'].corr(merged_df['close'])

# --- Step 5: Display the result ---
print(f"Correlation between Bitcoin price and S&P 500 closing price: {correlation}")

Correlation between Bitcoin price and S&P 500 closing price: nan

In [76]:
import sqlite3
import pandas as pd
from pycoingecko import CoinGeckoAPI
from datetime import datetime, timedelta

# Initialize CoinGeckoAPI
cg = CoinGeckoAPI()

# --- Step 1: Fetch Ethereum historical price data (last 365 days from now) ---
coin_id_eth = 'ethereum'
vs_currency = 'usd'
# Define the date range to be the last 365 days from the current execution date
current_date = datetime.now()
from_date = int((current_date - timedelta(days=365)).timestamp())
to_date = int(current_date.timestamp())

etherum_data = cg.get_coin_market_chart_range_by_id(
    id=coin_id_eth,
    vs_currency=vs_currency,
    from_timestamp=from_date,
    to_timestamp=to_date
)

# Extract prices and create DataFrame
df_eth = pd.DataFrame(etherum_data['prices'], columns=['timestamp', 'price_usd'])
df_eth['date'] = pd.to_datetime(df_eth['timestamp'], unit='ms').dt.date
df_eth['coin_id'] = coin_id_eth
df_eth = df_eth[['date', 'price_usd']] # Keep only relevant columns

# --- Step 2: Fetch Nasdaq closing price data from stocks.db for the same period ---
# The Nasdaq query will remain for the full year 2025 as requested, and then we'll merge
conn_stocks = sqlite3.connect('stocks.db')
query_nasdaq = """
SELECT
    date,
    close
FROM
    Stock_prices
WHERE
    ticker = '^IXIC' AND date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY
    date ASC;
"""
df_nasdaq = pd.read_sql_query(query_nasdaq, conn_stocks)
conn_stocks.close()

# --- Step 3: Merge the two DataFrames on their common date column ---
df_eth['date'] = pd.to_datetime(df_eth['date'])
df_nasdaq['date'] = pd.to_datetime(df_nasdaq['date'])

merged_df = pd.merge(df_eth, df_nasdaq, on='date', how='inner')

# --- Step 4: Calculate the ETH/NASDAQ ratio ---
merged_df['eth_nasdaq_ratio'] = merged_df['price_usd'] / merged_df['close']

# --- Step 5: Display the result ---
print("Ethereum Price vs Nasdaq Closing Price Ratio (Available Period):")
print(merged_df[['date', 'price_usd', 'close', 'eth_nasdaq_ratio']].head())

# Check if merged_df is empty to provide informative message
if merged_df.empty:
    print("No common data found for the specified period. This might be due to missing data for Ethereum or Nasdaq in the given date range.")

Ethereum Price vs Nasdaq Closing Price Ratio (Available Period):
        date    price_usd         close  eth_nasdaq_ratio
0 2025-02-26  2495.315452  19075.259766          0.130814
1 2025-02-27  2325.853935  18544.419922          0.125421
2 2025-02-28  2305.322938  18847.279297          0.122316
3 2025-03-03  2517.338239  18350.189453          0.137183
4 2025-03-04  2148.199533  18285.160156          0.117483

In [84]:
import sqlite3
import pandas as pd

# --- Step 1: Fetch Nifty 50 data from stocks.db ---
conn_stocks = sqlite3.connect('stocks.db')
query_nifty = """
SELECT
    date AS trade_date,
    open AS open_price,
    close AS close_price
FROM
    Stock_prices
WHERE
    ticker = '^NSEI'
    AND date BETWEEN '2025-01-01' AND '2026-02-24'
ORDER BY
    date DESC;
"""
df_nifty = pd.read_sql_query(query_nifty, conn_stocks)
conn_stocks.close()

# --- Step 2: Fetch Cryptocurrency prices from market_analytics.db ---
conn_crypto = sqlite3.connect('market_analytics.db')
query_crypto = """
SELECT
    date AS trade_date,
    coin_id,
    price_usd
FROM
    Crypto_prices
WHERE
    coin_id IN ('bitcoin', 'ethereum', 'solana')
    AND date BETWEEN '2025-01-01' AND '2026-02-24'
ORDER BY
    date DESC;
"""
df_crypto = pd.read_sql_query(query_crypto, conn_crypto)
conn_crypto.close()

# Pivot crypto data to have separate columns for each coin's price
df_crypto_pivot = df_crypto.pivot_table(index='trade_date', columns='coin_id', values='price_usd').reset_index()
df_crypto_pivot.columns.name = None # Remove the columns name 'coin_id'

# --- Step 3: Merge DataFrames ---
merged_df = pd.merge(df_nifty, df_crypto_pivot, on='trade_date', how='inner')

# --- Step 4: Perform calculations ---
merged_df['nifty_pct_change'] = round(((merged_df['close_price'] - merged_df['open_price']) / merged_df['open_price']) * 100, 2)

# Rename columns to match the original query's aliases for crypto prices
merged_df = merged_df.rename(columns={
    'bitcoin': 'btc_price',
    'ethereum': 'eth_price',
    'solana': 'sol_price'
})

# --- Step 5: Display results ---
print("Combined Daily Data (Nifty 50, Bitcoin, Ethereum, Solana):")
# Adjusting print statement to only display columns that are currently available
# The KeyError happened because 'eth_price' and 'sol_price' were not in merged_df
# as the Crypto_prices table only contained Bitcoin data.
print(merged_df[['trade_date', 'close_price', 'btc_price', 'nifty_pct_change']].head())

Combined Daily Data (Nifty 50, Bitcoin, Ethereum, Solana):
   trade_date   close_price     btc_price  nifty_pct_change
0  2026-01-09  25683.300781  90983.515781             -0.61
1  2026-01-08  25876.849609  91257.155440             -0.88
2  2026-01-07  26140.750000  93666.863873             -0.01
3  2026-01-06  26178.699219  93926.795649             -0.04
4  2026-01-05  26250.300781  91373.215881             -0.32

In [85]:
import sqlite3
import pandas as pd

# --- Step 1: Fetch S&P 500 data from stocks.db ---
conn_stocks = sqlite3.connect('stocks.db')
query_spx = """
SELECT
    date AS trade_date,
    close
FROM
    Stock_prices
WHERE
    ticker = '^GSPC'
    AND date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    date ASC;
"""
df_spx = pd.read_sql_query(query_spx, conn_stocks)
conn_stocks.close()

# --- Step 2: Fetch Oil prices from market_analytics.db ---
conn_oil = sqlite3.connect('market_analytics.db')
query_oil = """
SELECT
    Date AS trade_date,
    price_usd
FROM
    Oil_prices
WHERE
    trade_date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    trade_date ASC;
"""
df_oil = pd.read_sql_query(query_oil, conn_oil)
conn_oil.close()

# Ensure 'trade_date' columns are in datetime format for merging and calculations
df_spx['trade_date'] = pd.to_datetime(df_spx['trade_date'])
df_oil['trade_date'] = pd.to_datetime(df_oil['trade_date'])

# --- Step 3: Calculate daily percentage change for S&P 500 ---
df_spx['prev_close'] = df_spx['close'].shift(1)
df_spx['sp500_daily_pct'] = round(((df_spx['close'] - df_spx['prev_close']) / df_spx['prev_close']) * 100, 2)

# --- Step 4: Calculate daily percentage change for Oil prices ---
df_oil['prev_price'] = df_oil['price_usd'].shift(1)
df_oil['oil_daily_pct'] = round(((df_oil['price_usd'] - df_oil['prev_price']) / df_oil['prev_price']) * 100, 2)

# --- Step 5: Merge the two DataFrames ---
merged_df = pd.merge(df_spx[['trade_date', 'close', 'sp500_daily_pct']],
                     df_oil[['trade_date', 'price_usd', 'oil_daily_pct']],
                     on='trade_date', how='inner')

# Rename columns for clarity as in the original SQL query
merged_df = merged_df.rename(columns={
    'close': 'sp500_level',
    'price_usd': 'oil_price_wti'
})

# --- Step 6: Display results ---
print("Combined Daily Data (S&P 500 and WTI Oil, including daily percentage changes):")
print(merged_df.head())

Combined Daily Data (S&P 500 and WTI Oil, including daily percentage changes):
  trade_date  sp500_level  sp500_daily_pct  oil_price_wti  oil_daily_pct
0 2025-01-02  5868.549805              NaN          73.79            NaN
1 2025-01-03  5942.470215             1.26          74.64           1.15
2 2025-01-06  5975.379883             0.55          74.31          -0.44
3 2025-01-07  5909.029785            -1.11          74.99           0.92
4 2025-01-08  5918.250000             0.16          73.99          -1.33

In [86]:
import sqlite3
import pandas as pd

# --- Step 1: Fetch Bitcoin price data from market_analytics.db ---
conn = sqlite3.connect('market_analytics.db')
query_btc = """
SELECT
    date AS trade_date,
    price_usd AS btc_price
FROM
    Crypto_prices
WHERE
    coin_id = 'bitcoin'
    AND date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    date ASC;
"""
df_btc = pd.read_sql_query(query_btc, conn)

# --- Step 2: Fetch Oil prices from market_analytics.db ---
query_oil = """
SELECT
    Date AS trade_date,
    price_usd AS oil_price_wti
FROM
    Oil_prices
WHERE
    Date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    Date ASC;
"""
df_oil = pd.read_sql_query(query_oil, conn)
conn.close()

# --- Step 3: Ensure 'trade_date' columns are in datetime format and sort ---
df_btc['trade_date'] = pd.to_datetime(df_btc['trade_date'])
df_oil['trade_date'] = pd.to_datetime(df_oil['trade_date'])

df_btc = df_btc.sort_values(by='trade_date')
df_oil = df_oil.sort_values(by='trade_date')

# --- Step 4: Calculate daily percentage returns ---
df_btc['btc_return_pct'] = round(df_btc['btc_price'].pct_change() * 100, 2)
df_oil['oil_return_pct'] = round(df_oil['oil_price_wti'].pct_change() * 100, 2)

# --- Step 5: Merge the two DataFrames ---
combined_df = pd.merge(df_btc, df_oil, on='trade_date', how='inner')

# --- Step 6: Select and display relevant columns ---
print("Bitcoin and Oil Prices with Daily Returns (2025-01-01 to 2026-02-25):")
print(combined_df[['trade_date', 'btc_price', 'oil_price_wti', 'btc_return_pct', 'oil_return_pct']].head())

Bitcoin and Oil Prices with Daily Returns (2025-01-01 to 2026-02-25):
  trade_date     btc_price  oil_price_wti  btc_return_pct  oil_return_pct
0 2025-02-26  88755.769336          68.87             NaN           -0.40
1 2025-02-27  83900.114965          70.62           -5.47            2.54
2 2025-02-28  84709.144778          69.97            0.96           -0.92
3 2025-03-03  94261.532865          68.63            9.60           -1.92
4 2025-03-04  86124.714187          68.47           -8.63           -0.23

In [67]:
import sqlite3
import pandas as pd
from pycoingecko import CoinGeckoAPI
from datetime import datetime, timedelta

# Initialize CoinGeckoAPI
cg = CoinGeckoAPI()

# --- Step 1: Fetch Ethereum historical price data (last 365 days from now) ---
coin_id_eth = 'ethereum'
vs_currency = 'usd'
# Define the date range to be the last 365 days from the current execution date
current_date = datetime.now()
from_timestamp = int((current_date - timedelta(days=365)).timestamp())
to_timestamp = int(current_date.timestamp())

# Convert timestamps to YYYY-MM-DD string format for SQL query
from_date_str = (current_date - timedelta(days=365)).strftime('%Y-%m-%d')
to_date_str = current_date.strftime('%Y-%m-%d')

etherum_data = cg.get_coin_market_chart_range_by_id(
    id=coin_id_eth,
    vs_currency=vs_currency,
    from_timestamp=from_timestamp,
    to_timestamp=to_timestamp
)

# Extract prices and create DataFrame
df_eth = pd.DataFrame(etherum_data['prices'], columns=['timestamp', 'price_usd'])
df_eth['date'] = pd.to_datetime(df_eth['timestamp'], unit='ms').dt.date
df_eth['coin_id'] = coin_id_eth
df_eth = df_eth[['date', 'price_usd']] # Keep only relevant columns

# --- Step 2: Fetch Nasdaq closing price data from stocks.db for the same period ---
conn_stocks = sqlite3.connect('stocks.db')
query_nasdaq = f"""
SELECT
    date,
    close
FROM
    Stock_prices
WHERE
    ticker = '^IXIC' AND date BETWEEN '{from_date_str}' AND '{to_date_str}'
ORDER BY
    date ASC;
"""
df_nasdaq = pd.read_sql_query(query_nasdaq, conn_stocks)
conn_stocks.close()

# --- Step 3: Merge the two DataFrames on their common date column ---
df_eth['date'] = pd.to_datetime(df_eth['date'])
df_nasdaq['date'] = pd.to_datetime(df_nasdaq['date'])

merged_df = pd.merge(df_eth, df_nasdaq, on='date', how='inner')

# --- Step 4: Calculate the ETH/NASDAQ ratio ---
merged_df['eth_nasdaq_ratio'] = merged_df['price_usd'] / merged_df['close']

# --- Step 5: Display the result ---
print("Ethereum Price vs Nasdaq Closing Price Ratio (Available Period):")
print(merged_df[['date', 'price_usd', 'close', 'eth_nasdaq_ratio']].head())

# Check if merged_df is empty to provide informative message
if merged_df.empty:
    print("No common data found for the specified period. This might be due to missing data for Ethereum or Nasdaq in the given date range.")

Ethereum Price vs Nasdaq Closing Price Ratio (Available Period):
        date    price_usd         close  eth_nasdaq_ratio
0 2025-02-26  2495.315452  19075.259766          0.130814
1 2025-02-27  2325.853935  18544.419922          0.125421
2 2025-02-28  2305.322938  18847.279297          0.122316
3 2025-03-03  2517.338239  18350.189453          0.137183
4 2025-03-04  2148.199533  18285.160156          0.117483

In [88]:
import sqlite3
import pandas as pd
from pycoingecko import CoinGeckoAPI
from datetime import datetime, timedelta

# Initialize CoinGeckoAPI
cg = CoinGeckoAPI()

# Define a consistent date range for the last 365 days
current_date = datetime.now()
from_timestamp = int((current_date - timedelta(days=365)).timestamp())
to_timestamp = int(current_date.timestamp())
from_date_str = (current_date - timedelta(days=365)).strftime('%Y-%m-%d')
to_date_str = current_date.strftime('%Y-%m-%d')

# --- 1. Fetch S&P 500 data from stocks.db ---
conn_stocks = sqlite3.connect('stocks.db')
query_spx = f"""
SELECT
    date AS trade_date,
    close AS sp500_close
FROM
    Stock_prices
WHERE
    ticker = '^GSPC'
    AND date BETWEEN '{from_date_str}' AND '{to_date_str}'
ORDER BY
    date ASC;
"""
df_spx = pd.read_sql_query(query_spx, conn_stocks)
conn_stocks.close()
df_spx['trade_date'] = pd.to_datetime(df_spx['trade_date'])
df_spx = df_spx.sort_values(by='trade_date')
df_spx['prev_sp'] = df_spx['sp500_close'].shift(1)
df_spx['sp500_daily_pct'] = round(((df_spx['sp500_close'] - df_spx['prev_sp']) / df_spx['prev_sp']) * 100, 2)

# --- 2. Fetch Nifty 50 data from stocks.db ---
conn_stocks = sqlite3.connect('stocks.db') # Re-establish connection or ensure it's open
query_nifty = f"""
SELECT
    date AS trade_date,
    close AS nifty_close
FROM
    Stock_prices
WHERE
    ticker = '^NSEI'
    AND date BETWEEN '{from_date_str}' AND '{to_date_str}'
ORDER BY
    date ASC;
"""
df_nifty = pd.read_sql_query(query_nifty, conn_stocks)
conn_stocks.close()
df_nifty['trade_date'] = pd.to_datetime(df_nifty['trade_date'])
df_nifty = df_nifty.sort_values(by='trade_date')

# --- 3. Fetch Bitcoin data from market_analytics.db ---
conn_crypto = sqlite3.connect('market_analytics.db')
query_btc = f"""
SELECT
    date AS trade_date,
    price_usd AS btc_price_usd
FROM
    Crypto_prices
WHERE
    coin_id = 'bitcoin'
    AND date BETWEEN '{from_date_str}' AND '{to_date_str}'
ORDER BY
    date ASC;
"""
df_btc = pd.read_sql_query(query_btc, conn_crypto)
conn_crypto.close()
df_btc['trade_date'] = pd.to_datetime(df_btc['trade_date'])
df_btc = df_btc.sort_values(by='trade_date')
df_btc['prev_btc'] = df_btc['btc_price_usd'].shift(1)
df_btc['btc_daily_pct'] = round(((df_btc['btc_price_usd'] - df_btc['prev_btc']) / df_btc['prev_btc']) * 100, 2)

# --- 4. Fetch Ethereum data from CoinGecko API ---
etherum_data = cg.get_coin_market_chart_range_by_id(
    id='ethereum', vs_currency='usd', from_timestamp=from_timestamp, to_timestamp=to_timestamp
)
df_eth = pd.DataFrame(etherum_data['prices'], columns=['timestamp', 'eth_price_usd'])
df_eth['trade_date'] = pd.to_datetime(df_eth['timestamp'], unit='ms').dt.date
df_eth['trade_date'] = pd.to_datetime(df_eth['trade_date'])
df_eth = df_eth.sort_values(by='trade_date')

# --- 5. Fetch Tether data from CoinGecko API ---
tether_data = cg.get_coin_market_chart_range_by_id(
    id='tether', vs_currency='usd', from_timestamp=from_timestamp, to_timestamp=to_timestamp
)
df_tether = pd.DataFrame(tether_data['prices'], columns=['timestamp', 'tether_price_usd'])
df_tether['trade_date'] = pd.to_datetime(df_tether['timestamp'], unit='ms').dt.date
df_tether['trade_date'] = pd.to_datetime(df_tether['trade_date'])
df_tether = df_tether.sort_values(by='trade_date')
df_tether['usdt_peg_ratio'] = round(df_tether['tether_price_usd'] / 1.0, 4) # Tether should be pegged to 1 USD

# --- 6. Merge all DataFrames ---
merged_df = pd.merge(df_spx[['trade_date', 'sp500_close', 'sp500_daily_pct']], df_nifty[['trade_date', 'nifty_close']], on='trade_date', how='inner')
merged_df = pd.merge(merged_df, df_btc[['trade_date', 'btc_price_usd', 'btc_daily_pct']], on='trade_date', how='inner')
merged_df = pd.merge(merged_df, df_eth[['trade_date', 'eth_price_usd']], on='trade_date', how='inner')
merged_df = pd.merge(merged_df, df_tether[['trade_date', 'usdt_peg_ratio']], on='trade_date', how='inner')

# --- 7. Display results ---
print("Combined Market Data (Stocks and Cryptos with Daily % Changes):")
print(merged_df.head())

Combined Market Data (Stocks and Cryptos with Daily % Changes):
  trade_date  sp500_close  sp500_daily_pct   nifty_close  btc_price_usd  \
0 2025-02-26  5956.060059             0.01           NaN   88755.769336
1 2025-02-27  5861.569824            -1.59  22545.050781   83900.114965
2 2025-02-28  5954.500000             1.59  22124.699219   84709.144778
3 2025-03-03  5849.720215            -1.76  22119.300781   94261.532865
4 2025-03-04  5778.149902            -1.22  22082.650391   86124.714187

   btc_daily_pct  eth_price_usd  usdt_peg_ratio
0            NaN    2495.315452          0.9989
1          -5.47    2325.853935          0.9985
2           0.96    2305.322938          0.9991
3           9.60    2517.338239          1.0001
4          -8.63    2148.199533          0.9993

In [89]:
import sqlite3
import pandas as pd

# --- Step 1: Fetch S&P 500 data from stocks.db ---
conn_stocks = sqlite3.connect('stocks.db')
query_spx = """
SELECT
    date AS trade_date,
    close AS sp500_close
FROM
    Stock_prices
WHERE
    ticker = '^GSPC'
    AND date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    date ASC;
"""
df_spx = pd.read_sql_query(query_spx, conn_stocks)
conn_stocks.close()

# --- Step 2: Fetch Oil prices from market_analytics.db ---
conn_analytics = sqlite3.connect('market_analytics.db')
query_oil = """
SELECT
    Date AS trade_date,
    price_usd AS oil_wti_price
FROM
    Oil_prices
WHERE
    Date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    Date ASC;
"""
df_oil = pd.read_sql_query(query_oil, conn_analytics)

# --- Step 3: Fetch Bitcoin data from market_analytics.db ---
query_btc = """
SELECT
    date AS trade_date,
    price_usd AS btc_price
FROM
    Crypto_prices
WHERE
    coin_id = 'bitcoin'
    AND date BETWEEN '2025-01-01' AND '2026-02-25'
ORDER BY
    date ASC;
"""
df_btc = pd.read_sql_query(query_btc, conn_analytics)
conn_analytics.close()

# Ensure 'trade_date' columns are in datetime format for merging and calculations
df_spx['trade_date'] = pd.to_datetime(df_spx['trade_date'])
df_oil['trade_date'] = pd.to_datetime(df_oil['trade_date'])
df_btc['trade_date'] = pd.to_datetime(df_btc['trade_date'])

# --- Step 4: Calculate daily percentage changes ---
df_spx['prev_close'] = df_spx['sp500_close'].shift(1)
df_spx['sp500_return'] = round(((df_spx['sp500_close'] - df_spx['prev_close']) / df_spx['prev_close']) * 100, 2)

df_oil['prev_price'] = df_oil['oil_wti_price'].shift(1)
df_oil['oil_return'] = round(((df_oil['oil_wti_price'] - df_oil['prev_price']) / df_oil['prev_price']) * 100, 2)

df_btc['prev_price'] = df_btc['btc_price'].shift(1)
df_btc['btc_return'] = round(((df_btc['btc_price'] - df_btc['prev_price']) / df_btc['prev_price']) * 100, 2)

# --- Step 5: Merge all DataFrames ---
merged_df = pd.merge(df_spx[['trade_date', 'sp500_close', 'sp500_return']],
                     df_oil[['trade_date', 'oil_wti_price', 'oil_return']],
                     on='trade_date', how='inner')
merged_df = pd.merge(merged_df,
                     df_btc[['trade_date', 'btc_price', 'btc_return']],
                     on='trade_date', how='inner')

# --- Step 6: Display results ---
print("Combined Daily Data (S&P 500, WTI Oil, and Bitcoin with Daily Returns):")
print(merged_df.head())

Combined Daily Data (S&P 500, WTI Oil, and Bitcoin with Daily Returns):
  trade_date  sp500_close  sp500_return  oil_wti_price  oil_return  \
0 2025-02-26  5956.060059          0.01          68.87       -0.40
1 2025-02-27  5861.569824         -1.59          70.62        2.54
2 2025-02-28  5954.500000          1.59          69.97       -0.92
3 2025-03-03  5849.720215         -1.76          68.63       -1.92
4 2025-03-04  5778.149902         -1.22          68.47       -0.23

      btc_price  btc_return
0  88755.769336         NaN
1  83900.114965       -5.47
2  84709.144778        0.96
3  94261.532865        9.60
4  86124.714187       -8.63

# Streamlit App

In [106]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-02-25 11:32:48--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.2.0/cloudflared-linux-amd64 [following]
--2026-02-25 11:32:48--  https://github.com/cloudflare/cloudflared/releases/download/2026.2.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/f9298ca8-89c8-41fe-a51f-e24cb2059878?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-02-25T12%3A23%3A28Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-02-25T11%3A23%3A02Z&ske=2026-02-25T12%3A23%3A28Z&sks=b&skv=2018-11-09&sig=BYhwtsuqExia9j3WwW1DZZKnoVHWyopuMfykJVQNsm4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MjAyMDg0NywibmJmIjoxNzcyMDE5MDQ3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.M619EzQ6N60P6XaWfXsDLQCDulPVe_D47F6JSUAYHV8&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-02-25 11:32:48--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/f9298ca8-89c8-41fe-a51f-e24cb2059878?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-02-25T12%3A23%3A28Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-02-25T11%3A23%3A02Z&ske=2026-02-25T12%3A23%3A28Z&sks=b&skv=2018-11-09&sig=BYhwtsuqExia9j3WwW1DZZKnoVHWyopuMfykJVQNsm4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MjAyMDg0NywibmJmIjoxNzcyMDE5MDQ3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.M619EzQ6N60P6XaWfXsDLQCDulPVe_D47F6JSUAYHV8&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39289207 (37M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64.5’

cloudflared-linux-a 100%[===================>]  37.47M   130MB/s    in 0.3s

2026-02-25 11:32:48 (130 MB/s) - ‘cloudflared-linux-amd64.5’ saved [39289207/39289207]

nohup: appending output to 'nohup.out'

In [116]:
%%writefile app.py
import streamlit as st
import pandas as pd
import sqlite3
import yfinance as yf
from datetime import datetime, timedelta

# --- DATABASE & DATA FETCHING ---
@st.cache_resource
def init_db():
    conn = sqlite3.connect('market_data.db', check_same_thread=False)
    # Generate dummy data for Dashboard/SQL Runner
    dates = [(datetime.now() - timedelta(days=i)).strftime('%Y-%m-%d') for i in range(100)]
    dates.reverse()

    btc = pd.DataFrame({'date': dates, 'price': [90000 + (i*150) for i in range(100)]})
    oil = pd.DataFrame({'date': dates, 'price': [70 + (i*0.2) for i in range(100)]})
    sp500 = pd.DataFrame({'date': dates, 'price': [5000 + (i*5) for i in range(100)]})
    nifty = pd.DataFrame({'date': dates, 'price': [22000 + (i*10) for i in range(100)]})

    btc.to_sql('bitcoin', conn, if_exists='replace', index=False)
    oil.to_sql('oil', conn, if_exists='replace', index=False)
    sp500.to_sql('sp500', conn, if_exists='replace', index=False)
    nifty.to_sql('nifty', conn, if_exists='replace', index=False)
    return conn

conn = init_db()

# --- SIDEBAR NAVIGATION ---
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Market Dashboard", "SQL Query Runner", "Top 3 Crypto Analysis"])

# --- PAGE 1 & 2 (Previous Logic) ---
if page == "Market Dashboard":
    st.title("📈 Market Dashboard")
    col1, col2 = st.columns(2)
    start_date = col1.date_input("Start Date", datetime.now() - timedelta(days=30))
    end_date = col2.date_input("End Date", datetime.now())

    query = f"SELECT b.date, b.price AS BTC, o.price AS Oil, s.price AS SP500, n.price AS NIFTY FROM bitcoin b JOIN oil o ON b.date = o.date JOIN sp500 s ON b.date = s.date JOIN nifty n ON b.date = n.date WHERE b.date BETWEEN '{start_date}' AND '{end_date}'"
    df = pd.read_sql(query, conn)
    if not df.empty:
        st.dataframe(df, use_container_width=True)

elif page == "SQL Query Runner":
    st.title("🔍 SQL Query Runner")
    queries = {"Join Summary": "SELECT b.date, b.price as BTC, o.price as Oil FROM bitcoin b JOIN oil o ON b.date = o.date LIMIT 10"}
    sql_input = st.text_area("SQL Editor", queries["Join Summary"], height=150)
    if st.button("Run Query"):
        st.dataframe(pd.read_sql(sql_input, conn), use_container_width=True)

# --- PAGE 3: TOP 3 CRYPTO ANALYSIS ---
else:
    st.title("🪙 Top 3 Crypto Analysis")

    # 1. Selection
    crypto_mapping = {
        "Bitcoin (BTC)": "BTC-USD",
        "Ethereum (ETH)": "ETH-USD",
        "Solana (SOL)": "SOL-USD"
    }
    selected_name = st.selectbox("Select Cryptocurrency", list(crypto_mapping.keys()))
    ticker = crypto_mapping[selected_name]

    # 2. Date Filter
    col1, col2 = st.columns(2)
    start_dt = col1.date_input("From", datetime.now() - timedelta(days=60))
    end_dt = col2.date_input("To", datetime.now())

    # 3. Fetch Real Data
    with st.spinner(f'Fetching {selected_name} data...'):
        data = yf.download(ticker, start=start_dt, end=end_dt)

    if not data.empty:
        # Flatten columns if multi-index (common in newer yfinance)
        data = data[['Close']].reset_index()
        data.columns = ['Date', 'Price']

        # 4. Display Trend Chart
        st.subheader(f"{selected_name} Price Trend")
        st.line_chart(data.set_index('Date'))

        # 5. Display Table
        st.subheader("Daily Price Data")
        st.dataframe(data.sort_values(by='Date', ascending=False), use_container_width=True)
    else:
        st.error("No data found for this period.")

Overwriting app.py

In [115]:
!streamlit run /content/app.py &>/content/logs.txt &  # here instead of app.py please rename with your file name

In [114]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://picks-canal-style-pavilion.trycloudflare.com